### ISSUE TITLE
Volta doesn't load pinned engines

### ISSUE THREAD

**Issue by diego-toro** [volta-cli/volta#1004]
I've been working with NVM for quite a while now and wanted to include volta as a replacement in my old setup. But seems it's not lading the node version I pinned. 

I have this on my package.json

```json
{
  "volta": {
    "node": "14.17.0",
    "yarn": "1.22.10"
  },
}
```

When I hit `node -v` in my folder I got 

```
v16.3.0
```

Not even the REPL

```
$ node
Welcome to Node.js v16.3.0.
Type ".help" for more information.
>
```

Not sure if it has problems with NVM maybe?

Do I have to remove nvm to make volta work properly?

**Comment by IngenieroLata** [comment]
Hi @charlespierce! Thanks for replying back. I don’t think removing nvm is a good idea for me at the moment since I have plenty of projects that rely on it. But let’s dig into it.

Here's what I get from `which -a node`

```
/Users/diegotoro/.volta/bin/node
/Users/diegotoro/.volta/bin/node
/Users/diegotoro/.nvm/versions/node/v12.22.1/bin/node
```

Regarding my `.zshrc` indeed I have the PATH for nvm first and then volta.

```
# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# Volta
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
```

And yes commenting the NVM setup let volta work just fine.

So. Is there a way to tell volta to fallback setups?

**Comment by charlespierce** [comment]
Huh, that's strange because Volta _does_ appear to be winning in that case. For a little more debugging, there are two things to check:

- Does the symlink at `~/.volta/bin/node` actually point to something, and does that file that it points to exist (it should be named `volta-shim`)?
- Run `VOLTA_LOGLEVEL=debug node -v`, which should (if Volta is actually running) output additional information about what Volta found and the decisions it made. If you don't see any extra output then Volta definitely isn't running, if you do, then we can probably use that to narrow down the problem further.

**Comment by IngenieroLata** [comment]
I got as a result for symlink and volta-shim

```
lerna -> /Users/diegotoro/.volta/bin/volta-shim
node -> /Users/diegotoro/.volta/bin/volta-shim
npm -> /Users/diegotoro/.volta/bin/volta-shim
npx -> /Users/diegotoro/.volta/bin/volta-shim
verdaccio -> /Users/diegotoro/.volta/bin/volta-shim
volta
volta-migrate
volta-shim
yarn -> /Users/diegotoro/.volta/bin/volta-shim
```

And `VOLTA_LOGLEVEL=debug node -v`
```
[verbose] node@14.17.0 has already been fetched, skipping download
[verbose] yarn@1.22.10 has already been fetched, skipping download
[verbose] Active Image:
    Node: 14.17.0 from project configuration
    npm: 6.14.13 from project configuration
    Yarn: 1.22.10 from project configuration
v14.17.0
[verbose] No custom hooks found
```

For some reason now it's working. I just inverted the .zshrc setup. Now its

```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
```

**Comment by charlespierce** [comment]
@IngenieroLata Glad to hear it's working! Sometimes shells / terminals will cache the lookup results even when `PATH` changes, so it's possible that something like that happened.

Everything looks to be set up correctly, so it should be consistent. Let us know if it stops working again!

**Comment by diego-toro** [comment]
Thank you very much! @charlespierce
