### ISSUE TITLE
Please add support for arm64

### ISSUE THREAD

**Issue by mainendra** [volta-cli/volta#1006]

**Comment by charlespierce** [comment]
Hi @mainendra, can you clarify a bit what you mean by "support for arm64"? Are you referring to Arm64 Linux? Currently we have support in the code itself for that Architecture, but we don't create pre-built binaries. So you should be able to build from source, but the default installer doesn't have binaries to use.

If so, we can definitely investigate creating those binaries as part of our release, however I'm not familiar with the range of distros that support Arm64, so it may take a bit of work to make sure that we compile it correctly to work across a large range of distros.

If you're referring to the M1 MacOS Arm64, that should work out of the box already. If you're seeing problems, then that's a bug.

**Comment by mainendra** [comment]
@charlespierce - thanks. I'm using ubuntu on raspberry pi and default installation throwing an error that arm64 is not supported. But I'll try local build and see if it works. Yes, this is not a bug but feature request. Thanks again.

**Comment by sirreal** [comment]
I ran into this recently. I was able to build Volta from source on a Raspberry PI. The only difficulty I had was that the `os_info` dependency would not build. I solved this by upgrading to the latest version of the next major release `2.0.8`. After that, I was able to install and use Volta on a Raspberry Pi.

@charlespierce is there a reason the pre-built binaries are not provided? I'd be happy to help if it's a question of setting things up.

**Comment by charlespierce** [comment]
Hi @sirreal, the primary reason we don't have pre-built binaries for Linux arm64 is just bandwidth: we haven't gotten around to it. We'd love to have a contribution to add that, if you're interested in taking that on! One thing to consider would be the different OpenSSL versions: Currently we have to create 3 different Linux builds (for x64), since there are different versions of OpenSSL to link against (1.0.x, 1.1.x, and the custom one used by RHEL / CentOS), so there may need to be some testing around that for building the arm64 binaries.

Beyond that, the main steps would be including those builds in the GitHub actions (along side the other production builds) and updating the installer script to support that architecture.

**Comment by chriskrycho** [comment]
I think this is resolved in our v2.0.0 release, @charlespierce?

**Comment by charlespierce** [comment]
Yes, this is resolved now (after making a fix to the installer 😅). The `get.volta.sh` installer will correctly detect Linux ARM and install that version.
