### ISSUE TITLE
I can't execute command-line tools using rosetta

### ISSUE THREAD

**Issue by chungweileong94** [volta-cli/volta#1008]
I notice that I can't command-line tools like `npm`, etc with rosetta on my Apple M1 machine.

A bit of context here, I mainly working on React Native apps, because some libraries required me to build the project with x86 arch. Usually (if I was using `nvm`), I will need to run this command `arch -x86_64 npx react-native run-ios` in order to build my project. 

So I assume I can call the same command with volta, as the command is not an nvm-specific thing. However, it keeps throwing 
```
arch: posix_spawnp: npx: Bad CPU type in executable
```

The workaround that I found is I have to find out the location of the nvm with `volta which nvm`, then execute directly from there
```
arch -x86_64 /Users/chungwei/.volta/tools/image/node/16.4.0/bin/npx react-native run-ios
```

I think it's something to do with the way that volta handling the symlink?

**Comment by charlespierce** [comment]
Hi @chungweileong94, I think you're correct. The way that Volta works is that all of the binaries (e.g. `node`, `npx`, etc.) are actually symlinks to the `volta-shim` executable. That executable does the detection of the appropriate version and then calls out to the underlying command. Unfortunately for what you're trying to do, that executable (`volta-shim`) is a native M1 binary, which is why you get errors about the CPU type.

The workaround for that is, as you noted, using `volta which` to determine the underlying executable and then running that directly with `arch`. You should be able to combine those into a single command:

```
arch -x86_64 $(volta which npx) react-native run-ios
```

Another alternative, depending on your needs, would be to install the x86_64 version of Volta itself. This will cause it (and all of the Node versions that it downloads) to _all_ run using Rosetta 2. That will mean that you don't even need to use `arch -x86_64` to get the appropriate react-native executable, however it will also mean that you never get the native binaries. I don't have my own M1 mac to test, but I _believe_ you should be able to do that with:

```
curl https://get.volta.sh | arch -x86_64 bash
```

It's possible that the `bash` executable isn't a fat binary, however, so that may not work properly.

**Comment by chungweileong94** [comment]
> Hi @chungweileong94, I think you're correct. The way that Volta works is that all of the binaries (e.g. `node`, `npx`, etc.) are actually symlinks to the `volta-shim` executable. That executable does the detection of the appropriate version and then calls out to the underlying command. Unfortunately for what you're trying to do, that executable (`volta-shim`) is a native M1 binary, which is why you get errors about the CPU type.
> 
> The workaround for that is, as you noted, using `volta which` to determine the underlying executable and then running that directly with `arch`. You should be able to combine those into a single command:
> 
> ```
> arch -x86_64 $(volta which npx) react-native run-ios
> ```
> 
> Another alternative, depending on your needs, would be to install the x86_64 version of Volta itself. This will cause it (and all of the Node versions that it downloads) to _all_ run using Rosetta 2. That will mean that you don't even need to use `arch -x86_64` to get the appropriate react-native executable, however it will also mean that you never get the native binaries. I don't have my own M1 mac to test, but I _believe_ you should be able to do that with:
> 
> ```
> curl https://get.volta.sh | arch -x86_64 bash
> ```
> 
> It's possible that the `bash` executable isn't a fat binary, however, so that may not work properly.

Yeah, `$(volta which npx)` works the best work for me. I ended up having an alias to speed up things, in the near future everything should support native arm anyway🤞 
```
alias rosetta="arch -x86_64"
alias rosetta-npx="rosetta $(volta which npx)"
```
Thx for the tip @charlespierce
