### ISSUE TITLE
can't uninstall node 

### ISSUE THREAD

**Issue by Sepush** [volta-cli/volta#1013]
can't uninstall node by `volta uninstall node`
system: Win10 21H1
![image](https://user-images.githubusercontent.com/39197136/129341228-1c97e0b3-0ca7-457d-b117-998a52fe3140.png)

**Comment by charlespierce** [comment]
Hi @Sepush, this is tracked under #327. If you've got a specific use-case for uninstalling a Node version (note that Volta will automatically download new versions that it needs when it sees them, so it's possible for it to get re-downloaded), would you mind adding it to that issue?

**Comment by andrewplummer** [comment]
This issue was created less than a month ago but trying to follow up on a very simple question (why does `volta uninstall` not work the same as `volta install`?) leads down a rabbit hole that raises more questions than it answers:

- why is "notion" being mentioned in the same thread as "volta"?
- why is "notion" being mentioned in this repo at all?
- what *IS* "notion"?
- is everything they're talking about in all these threads features that will only become available in a successor to volta or do they actually pertain to `volta` even though they say `notion`?
- if notion is a successor to volta then why isn't it mentioned in either readme?
- if volta is the successor to notion then why isn't mentioned in either readme? also why is notion a fork of volta?
- if volta is the successor to notion then why does the project readme say "This project is just getting started." even though it appears to be dead?

I shouldn't be asking any of this here, but people are going to arrive here because volta clearly doesn't work as expected, either in a self-consistent manner or aligned with npm/yarn. And they're going to arrive with no context.

I have 3 requests that I think are reasonable. They will also save you from ever reading this again:

1. Could you please answer the above questions and then dump those answers into the volta README as well as the notion README (if possible)?
2. Can we add a link to #327 in the error message when running `volta uninstall node`?
3. Can we add a link to one of the relevant issues when running `volta uninstall node@x.x.x` which unexpectedly fails when a version clearly exists.

**Comment by andrewplummer** [comment]
I'm not asking to update the comment threads (or even the titles) of course. I'm still not sure why it says "notion" in them, I suppose when moving a repo it can bring across entire comment threads? Definitely confusing but I get it.

OK so the repo I found [here](https://github.com/rwjblue/notion) was just some random fork. No idea how I got there but never would have found it if there was some (any) mention in the readme about what notion is. There wasn't, so I kept searching and ended up there.

Of course the name is well established for *you*. However I've been using volta for years and had no idea it was called "notion". Certainly a first time user would not.

It's very simple, your comment threads mention notion everywhere, so it needs to go into the readme. It doesn't matter where, it can be at the very end. I see "notion" in the comments, have no idea what it is so of course I go to the readme and hit command F. A link to the blog post is just dandy.

**Comment by charlespierce** [comment]
> Of course the name is well established for you. However I've been using volta for years and had no idea it was called "notion". Certainly a first time user would not.

My language wasn’t as precise as I intended, but this is what I meant when I said the name is well-established. This project has been called Volta for well over 2 years now. The fact that’s once had a different name is a historical detail, not a major piece of the project.

The README is intended to be a high-level overview of the project; adding in a mention of a long-discarded name doesn’t further that goal, and can actually invite more confusion. One of the reasons for changing the name was because there were questions about whether we were connected to notion.so. Featuring that name in the README could serve to bring those questions back.

Given that there are small minority of issues that use the old name and that there won’t be new ones since the name has changed, I would lean more towards including a note in those issues about the name change.

**Comment by andrewplummer** [comment]
> This project has been called Volta for well over 2 years now. The fact that’s once had a different name is a historical detail, not a major piece of the project.

If it's mentioned all over the comments then most certainly yes, it is a major detail. Even if it were a minor one it deserves explanation.

> The README is intended to be a high-level overview of the project

The README is intended to answer basic questions that may arise when attempting to use your software. If you having entire comment threads mentioning two different tools interchangeably with no explanation as to how they are distinct, then yes, that part belongs in the README.

> One of the reasons for changing the name was because there were questions about whether we were connected to notion.so. Featuring that name in the README could serve to bring those questions back.

As opposed to featuring it everywhere in the comments without an explanation? You've got 173 issues with "notion" mentioned in them. You even have 18 **open** issues using that name interchangeably without explanation. [Here's a random example](https://github.com/volta-cli/volta/issues/327). How is a tiny clarification at the bottom of the readme is going to somehow invite confusion?

- "`volta` was renamed from `notion`"
- we are not affiliated with notion.so

^ That is literally all you need. I'm fundamentally baffled by your reasoning that leaving anything *out* of the documentation is going to prevent confusion. Is it a legal issue? If so then fair enough but in that case you *really* better start scrubbing your comments. For the record yes I 100% ended up at notion.so after not finding anything in the docs either here or on the site so I remain somewhat unpersuaded by your argument.

**Comment by charlespierce** [comment]
> The README is intended to answer basic questions that may arise when attempting to use your software. If you having entire comment threads mentioning two different tools interchangeably with no explanation as to how they are distinct, then yes, that part belongs in the README.

I think this might be the core of the disconnect: Knowing that Volta used to be named Notion _isn’t_ necessary to use the software.

The vast majority of issues which reference it are closed and no longer relevant. There won’t be any new issues that reference the old name because the new name is well-established for the project. Of the open issues, most of them are tracking issues for internal clean-up tasks that haven’t been picked up, not things that would be needed to understand how to use the software.

There are roughly 5 issues that exist from before the name change and discuss features / use-cases that are still outstanding in Volta. And even for those, most users don’t run into the underlying concerns they address.

It seems like adding a note / comment to those specific issues would be a lot more helpful than adding a blanket statement to the README: For users like yourself that are coming across them for the first time, it adds the necessary context right where it’s needed.

I absolutely apologize for the confusion caused in this case (which is unfortunately one of the few open issues from before the change that involves a larger piece of work). I definitely want to prevent that in the future. My disagreement is mostly with making sure we present it in the most effective way for the most users. For a new user who hasn’t wound up on one of the outstanding threads, mentioning the old name is an irrelevant detail. It’s only when you find yourself reading about an issue where the original comments are referencing a different name that it becomes important.

**Comment by andrewplummer** [comment]
> I think this might be the core of the disconnect: Knowing that Volta used to be named Notion isn’t necessary to use the software.

It certainly is when things aren't working as expected and you come to GitHub hoping things will make sense, as was the case here.

Again, 175 issues, 18 are open. Even if these are closed they could easily be an entry point from Google or god knows where. Even if you changed each of these threads, someone out in an old post in the wild might mention notion and get redirected here and wonder what's going on.

> My disagreement is mostly with making sure we present it in the most effective way for the most users.

You make it sound like I want a big banner across the top of the site. The project is established, I get it. I'm talking about having *some way* to find this information. It doesn't have to be directly in the readme btw. It can be an "other" page. It can be other > other > other for all it matters. Right now it's *nowhere*, readme or site. Someone has a question and needs it answered for things to make sense. There's simply no way that deliberately hiding this information can benefit people trying to use your software.

> For a new user who hasn’t wound up on one of the outstanding threads, mentioning the old name is an irrelevant detail.

Of course. Did you think I meant that I wanted it listed in each and every thread, even those not mentioning notion? I'm asking for something so basic I'm genuinely perplexed (and a bit intrigued) that it would have any pushback at all. I'm simply for a detail about the project that can clearly alleviate confusion to be accessible somewhere, *anywhere*.

**Comment by charlespierce** [comment]
I don’t have any pushback on the idea of adding the info to the docs somewhere, my concerns were specifically about the idea of adding it to the README. That file is the entry point to the repo—for many, the project itself—and a non-trivial amount of work went into figuring out what it should contain. It’s not intended to be an FAQ or place to provide answers to questions that have come up in the past.

An FAQ actually would be useful, and would be the perfect place to answer this question, along with a link to the blog post. I’ll look into creating something like that.

**Comment by andrewplummer** [comment]
FAQ is fine, as long as it's accessible from either the readme or the site.

**Comment by andrewplummer** [comment]
If you're going to bury it though, it needs to be searchable. Not necessarily within the site but by search engines. In fact, that's far more important. Again, we're talking about users with a specific question, so whatever whimsical IA standards you've decided a readme should have need not apply. All you need to do is provide a way for people to quickly figure out a "minor detail" of the project, ie. what' it's actually called.

Right now searching "volta notion" on Google shows [this blog post](https://blog.volta.sh/2019/02/05/state-of-the-notion/):

> The Volta Blog
> State of the Notion
> FEBRUARY 5, 2019 • DAVE HERMAN
> Notion is a JavaScript toolchain manager, making sure you always get the right version of Node, package managers like npm and Yarn, and JS command-line tools. Best of all, Notion makes tool requirements declarative and reproducible by using package.json to remember and launch the right versions of a project’s required tools, so developers and users always see their projects build and run in a consistent environment.

Like just........what? Reading through it 5 times I think I finally get what's happened here but please read through this and think about it from the perspective of someone who arrived here seeded with the words "volta" and "notion" in their head. The name is out there, it's going to happen. Having open (and still relevant) issues using the name without explanation doesn't help, but it's not the end of the story. Your software doesn't exist in a bubble.

**Comment by andrewplummer** [comment]
First off I see that you've added a note in the blog post as well as the open issues still mentioning notion. Awesome! It's a great start 👍 

But of course the open issues aren't the only problem. Users may arrive at a closed issue (as I did) from a search as they still contain lots of good information about issues other users have had. Or they could follow a link from an old blog post, word of mouth, anywhere really! The fact that this isn't anywhere in the readme or main site is still a problem.

### [But not to worry!](https://github.com/volta-cli/volta/issues/1148)

Your software doesn't exist in a bubble, but in our age that cuts both ways. We can all help to contribute to better documentation.

Cheers and thank you for this project. I really do appreciate it.
