### ISSUE TITLE
warn for or forbid `volta install 10`

### ISSUE THREAD

**Issue by bakkot** [volta-cli/volta#1016]
Coming from `nvm`, I've repeatedly found myself doing `volta install 10` intending to install `node@10`. Instead, that installs [some random package](https://www.npmjs.com/package/10). I expect it runs that project's `install` script, too, meaning that it's also running arbitrary code on my computer.

That seems bad.

I think it would be worth having the CLI stop you from doing this, or at least make you confirm that it's what you really wanted. That is, concretely, the CLI should have a warning when the package name starts with a decimal digit and there is no specified `@` version number.

(Even better would be if the CLI had different syntax for installing node vs installing random packages. It seems bad to overload `install` so much.)

**Comment by charlespierce** [comment]
Hi @bakkot, thanks for the suggestion! We actually do have some logic to handle the case when someone does `<package> <version>`, e.g. `volta install node 10`, since that _used_ to be our syntax in the early days.

I suspect we can repurpose some of that to handle the `volta install <version-like>` case for specifically this reason. @chriskrycho I think you did the initial logic for `volta install <package> <version-like>`, do you have a sense for how difficult it would be to also handle `volta install <version-like>` as an error?

**Comment by chriskrycho** [comment]
It had been long enough that I no longer had a sense, so I looked it up when I implemented it. The key bits are:

- [implementing the version parsing](https://github.com/volta-cli/volta/pull/383/files#diff-d62fc794b05c139f8620e3a0a4402934b2f7e157d8cdf9a2152c79814aad6c62R94-R125), as part of implementing volta-cli/rfcs#32
- [providing error cases for e.g. `volta install node 10`](https://github.com/volta-cli/volta/pull/403/files#diff-d62fc794b05c139f8620e3a0a4402934b2f7e157d8cdf9a2152c79814aad6c62R136-R191), which expanded on the logic introduced in the section linked above to provide useful errors
