### ISSUE TITLE
[BUG] Breaks `npm -g list`…

### ISSUE THREAD

**Issue by jcayzac** [volta-cli/volta#1017]
I'm using volta 1.0.1.

I have a few versions of npm installed:

```sh
$ ls ~/.volta/tools/image/npm
7.11.2  7.21.0  7.4.3
```

I'm using 7.21.0:

```sh
$ npm --version
7.21.0
```

I have globally-installed packages:

```sh
$ ls ~/.volta/tools/image/packages
pnpm
```

But `npm list` says otherwise 😢 

```sh
$ npm -g list
/Users/julien.cayzac/.volta/tools/image/node/16.5.0/lib
└── npm@7.19.1
```

Also, I never installed npm `7.19.1`.

I guess `npm list` is broken because volta put my globally-installed package in `~/.volta/tools/image/packages`, not under the per-npm-version npm prefix where they belong? The notion of a shared packages repo across versions of node and npm looks sexy but is broken: any new version of npm/node may break compatibility with modules built for a different version.

**Comment by charlespierce** [comment]
Hi @jcayzac, thanks for reporting this! I believe what you're seeing is the fact that `npm` by default uses the `node` directory as the default `prefix`. Volta's model has each package sandboxed, so they go into separate directories and don't show up under `npm -g list`. This is tracked in #1012, follow that for updates on getting `npm -g list` to work.

> The notion of a shared packages repo across versions of node and npm looks sexy but is broken: any new version of npm/node may break compatibility with modules built for a different version.

This is actually exactly why Volta's model works the way it does! Each global package is sandboxed and has its node version pinned so that it will continue to work the same even if your default Node version changes.

**Comment by charlespierce** [comment]
We've got more info on how the Node version pinning works in the docs: https://docs.volta.sh/advanced/packages as well as a blog post about the benefits that pinning provides (along with our automatic local delegation): https://blog.volta.sh/2019/06/18/global-installs-done-right/
