### ISSUE TITLE
[BUG] Updating node doesn't update npm's target dir for binaries

### ISSUE THREAD

**Issue by jcayzac** [volta-cli/volta#1018]
Until now my configuration was:

```json
  "volta": {
    "node": "16.5.0",
    "npm": "7.21.0"
  }
```

…and npm happily reported:

```sh
$ npm bin -g
/Users/julien.cayzac/.volta/tools/image/node/16.5.0/bin
```

Now I just updated to a more recent version of node:

```diff
   "volta": {
-    "node": "16.5.0",
+    "node": "16.7.0",
     "npm": "7.21.0"
   }
```

```sh
$ node --version
v16.7.0
```

However, npm now makes me sad:

```sh
$ npm bin -g
/Users/julien.cayzac/.volta/tools/image/node/16.5.0/bin
```

**Comment by charlespierce** [comment]
@jcayzac That's very odd! Do you happen to have `NPM_CONFIG_PREFIX` set in your environment variables? The PATH is being set up correctly (since `node --version` works), so `npm` should be looking at that directory.

That said, Volta's model puts globally installed packages into a separate directory entirely, which mostly invalidates the `npm bin -g` command anyway. Is there a specific use-case you're looking at where you need the output of `npm bin -g`?

**Comment by jcayzac** [comment]
> Do you happen to have NPM_CONFIG_PREFIX set in your environment variables?

No, but I noted my `~/.npmrc` got changed and has `prefix=/Users/julien.cayzac/.volta/tools/image/node/16.5.0` now. Wasn't me!

**Comment by charlespierce** [comment]
@jcayzac Odd! Volta doesn't touch `.npmrc`, so I wonder if there's something else out there that wrote that! Removing it should fix your issues, while figuring out what wrote it would help make sure it doesn't come back :+1:

**Comment by jcayzac** [comment]
Yes, the issue is gone not I removed it. I have no idea what package put it there, tho. OK, since it seems to be a very edgy edge case I guess this issue doesn't serve much purpose and should be closed.
Cheers.
