### ISSUE TITLE
Not supported for Mac OS High Sierra?

### ISSUE THREAD

**Issue by srinidhirao** [volta-cli/volta#1048]
I want to install Volta on one of our macs running High Sierra. This Mac is old and is not upgradable. I got an error while trying to install, I think this is trying to install the latest version. What is the release which is compatible with Mac OS High Sierra (version: 10.13.6)?

```
Server:slave server$ curl https://get.volta.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12319  100 12319    0     0  14067      0 --:--:-- --:--:-- --:--:-- 14062
  Installing latest version of Volta ()
    Checking for existing Volta installation
    Fetching archive for macOS, version 

curl: (22) The requested URL returned error: 404 
Error: Could not download Volta version ''. See https://github.com/volta-cli/volta/releases for a list of available releases

```

**Comment by charlespierce** [comment]
Hi @srinidhirao! Since it looks like the install script is failing to find the latest version, I suspect the issue you're seeing is related to #1035 and the Let's Encrypt root certificate changing. My first suggestion would be to take a look at the solution proposed here: https://github.com/volta-cli/volta/issues/1035#issuecomment-948904947

If that doesn't help, we can look at debugging more deeply, but the core issue seems to be the script can't figure out the latest version to download at all, not that it's an incompatible MacOS.

**Comment by srinidhirao** [comment]
@charlespierce That helped. I followed the instructions as in #1035  and was able to get it to work!

Thanks.
