### ISSUE TITLE
Switch from deprecated double-checked-cell to once_cell

### ISSUE THREAD

**Issue by chriskrycho** [volta-cli/volta#1074]
double-checked-cell [is deprecated](https://github.com/niklasf/double-checked-cell/blob/9cf94d75316ef441033ce4c80def7c1a8c7643fe/README.md#deprecated) and recommends migrating to `once_cell`. It's not urgent, but worth putting on our radar.

**Comment by charlespierce** [comment]
Oh nice! IIRC, at the time I looked at this `once_cell` didn't have the `get_or_try_init` method, which made it very awkward to initialize the cell with a fallible operation. That ergonomic API is ultimately what led me to `double-checked-cell`, but it looks like that's since been incorporated, so agreed we should look to switch over.
