### ISSUE TITLE
Why is "name" always added to root project in package-lock?

### ISSUE THREAD

**Issue by loxy** [volta-cli/volta#1120]
Hi,

if I install via Volta (`npm i`) it always adds `name` attribute to `package-lock.json`:
```json
{
  "name": "my-package-name",
  "version": "0.1.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "name": "my-package-name",  // <- problematic entry
      "version": "0.1.0",
      "dependencies": {
```
Generally, this is no problem. But in our team the others are using other tools, like NVM. And these tools are removing this entry again. So, it always leads to changes in Git. This is annoying. Any ideas?

Best regards,
Kersten

**Comment by chriskrycho** [comment]
The first diagnostic question is: what version of npm are those colleagues ending up using via nvm, and what version are you pinning via Volta? At first blush, I would expect this to be a choice made by npm, and therefore a problem resulting from folks having different versions (it's certainly nothing done by Volta directly: we don't touch lock files at *all*).

As an aside, this is a good argument for standardizing your team's toolchain (even if on nvm instead of Volta! Though obviously we have a preference 😉).

**Comment by loxy** [comment]
Yeah, I know. But I'm on Windows and NVM (for Windows) is quite outdated. And the guys are using the same NodeJS and NPM version as me. Weird. It is only added if I use Volta. Will investigate it further. Thank you!

Keep it open for now, but will come back!

**Comment by ljharb** [comment]
It’s something npm does; you’re probably using a newer version than they are.

**Comment by loxy** [comment]
Ok, found the issue. You are completely right! One guy was using an older version. Sorry for the confusion...
