### ISSUE TITLE
Typescript (tsc bin) not working

### ISSUE THREAD

**Issue by denik1981** [volta-cli/volta#1149]
I'm having problems trying to use `tsc` from the command line after installing typescript globally.
Seems this is calling `npx` under the hood and it cannot find the `tsc` bin. 
However it works well when using `volta run tsc`

**Steps to reproduce**:

- `curl https://get.volta.sh | bash`
- `volta install node`
- `volta install typescript`  _// Can be replaced with  `npm i typescript -g` as ​well_
- `tsc --version` _// Same happens calling `npx tsc --version`_

```
Need to install the following packages:
 ​tsc
Ok to proceed? (y)
```
- `volta which tsc`: $HOME/.volta/tools/image/packages/typescript/bin/tsc
- `$HOME/.volta/tools/image/packages/typescript/bin/tsc --version`: `Version 4.5.5`
- `node --version`: v16.13.2
- `npm --version`: 8.4.0
- `echo $PATH | tr : \\n | grep volta`: $HOME/.volta/bin`
_$HOME is already resolved to my /home/\<user\>/ directory_ 

**OS Version**
`uname -a`: `Linux LinuxOS 5.13.0-27-generic #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linu

**Comment by andrei9669** [comment]
have you tried to run `volta setup` and then `tsc` ?

**Comment by charlespierce** [comment]
Hi @denik1981, that's odd! We don't use `npx` internally for launching globals, though we follow a similar process. It looks like when you call `tsc --version` it's being intercepted by something else that is invoking `npx`. Is it possible you have a script somewhere doing that?

One extra piece of info that may help would be to look at the output of `which -a tsc`, to see if the Volta shim or some other unrelated script is first in your PATH. Also worth noting that it may help to restart your shell, since some shells do caching of binary lookup locations and ignore the normal PATH resolution once they have a cached location.

**Comment by denik1981** [comment]
@charlespierce Yes, seems I was having a shell alias for `tsc` pointing to `npx tsc`. My bad on this one. 
I recently installed a community shared list of useful shell aliases but I wouldn't imagine it would have one for `tsc`. 
I will close this because it is unrelated to volta. Thanks for the help!
