### ISSUE TITLE
Pin to wildcard?

### ISSUE THREAD

**Issue by jwalton** [volta-cli/volta#1151]
New volta user here, and I'm really enjoying it so far, but there's one thing that I find quite surprising.  If I run:

```sh
$ volta pin node@16
```

This writes:

```json
  "volta": {
    "node": "16.13.2"
  }
```

to my package.json, but I was expecting:

```json
  "volta": {
    "node": "16"
  }
```

This feels like I'm going to end up with three hundred different versions of node 16 installed on my system as node gets upgraded and package.json in infrequently accessed projects starts to lag behind.  I tried to manually modify the pinned version to be just "16", but volta doesn't seem to like that.

**Comment by chriskrycho** [comment]
@jwalton this is a key difference between Volta and other tools: we *only* do specific versions. That's what gives us the guarantees of reproducibility and reliability across different machines: that we know that everyone using Volta with a given project is guaranteed to be using the *exact* same version. That means it's possible to make sure everyone has the same fixes, and to avoid the "works on my machine" problem to a much greater degree.

Notice that this behavior is documented [here](https://docs.volta.sh/guide/#why-volta):

> Volta lets you choose your Node engine and package manager for a project once with one command:
>
> ```
> volta pin node@12
> ```
>
> Volta saves the exact version of the Node engine in your package.json so you can commit your selection to git. From that point on, every time you run Node inside your project directory, Volta automatically switches to that same version of Node you chose. Similarly, all your collaborators can do the same by installing Volta on their development machine.

(There are a number of other discussions of this across the repo history, but alas I do not have time at the moment to dig them all up!)

**Comment by jwalton** [comment]
> Volta automatically switches to that same version of Node you chose.

Ironically this is exactly the line that make me think something was wrong - volta didn't pin the version I chose, it pinned the version Volta chose.

I can understand the sentiment, and if this has already been hashed to death then my apologies, but I will point out that you can make this the default behavior and make "I need exactly this version of node" people happy, but you could *also* support pinning to a wildcard.  :)

> There are a number of other discussions of this across the repo history, but alas I do not have time at the moment to dig them all up!

Sorry - did a quick search for "pin wildcard" "node wildcard" and a few others, but didn't find anything.  :(

**Comment by charlespierce** [comment]
@jwalton Thanks for the question! As Chris mentioned, one of the core design goals of Volta is to allow for fully-reproducible builds, so that some environmental factor that completely outside of a project doesn't break your build in a confusing and hard-to-diagnose way.

Other important design goals that impact this are performance and transparency: With a wildcard, we either need to make a network request to look up the latest Node version on every invocation—which would be unacceptably slow—or we need to rely on the local cache. The latter would mean you would need to regularly think about the state of your local cache, which goes against our goal of having the experience of Volta be as seamless as possible (ideally once things are set up you don't even have to think about the fact that you're using it any more). For those reasons, we decided against supporting ranges / wildcard versions.

> Ironically this is exactly the line that make me think something was wrong - volta didn't pin the version I chose, it pinned the version Volta chose.

We can definitely look at the language here to make it more clear it will always pin a specific version, resolved when you run the command. Thanks for pointing out that interpretation!

> Sorry - did a quick search for "pin wildcard" "node wildcard" and a few others, but didn't find anything. :(

No worries here! It probably didn't pop up because most of the past discussion around this has been around supporting the `engines` key in `package.json`. The main technical reason we don't do that is because `engines` can be a wildcard / range. See [this comment](https://github.com/volta-cli/volta/issues/742#issuecomment-631588143) for more discussion there.

**Comment by douglasjunior** [comment]
> Other important design goals that impact this are performance and transparency: With a wildcard, we either need to make a network request to look up the latest Node version on every invocation—which would be unacceptably slow

NVM, for example, uses the most compatible version already installed.

**Comment by chriskrycho** [comment]
So it does, but that goes against the aim of reproducibility! If you have v22.0.0 installed and your coworker has v20.10.3 installed, the two of you will have *wildly* different results! Basically, our thinking is that there are already tools that will give you that behavior if you want it; the whole *point* of Volta is to give you *this* behavior.

**Comment by douglasjunior** [comment]
I understand your point, but some tools (like React Native or even some simpler backend apps) normally require only the major Node version, so the devs can reuse already installed node versions, saving disk space, network bandwidth, etc.

**Comment by chriskrycho** [comment]
That's understandable—it’s just a different tradeoff, and any of a number of other tools in the ecosystem should work well for you. (We’re not offended when folks use nvm or fnm or whatever else!)
