### ISSUE TITLE
volta-core: can't fetch node >=4.0.0 < 4.5.0 for win

### ISSUE THREAD

**Issue by sergeysedoy97** [volta-cli/volta#1160]
```
volta fetch node@4.4.5
error: Could not find Node version matching ">= 4.4.0 < 4.5.0" in the version registry.
```

You are trying to download the archive from `https://nodejs.org/dist/v4.4.5/node-v4.4.5-win-x64.zip`, but versions before 4.5.0 contain only `.msi` packages, as a workaround, you can use the `node.exe` binary in [win-x64](https://nodejs.org/dist/v4.4.5/win-x64/) and [win-x86](https://nodejs.org/dist/v4.4.5/win-x86/) folders.

**Comment by charlespierce** [comment]
Hi @sergeysedoy97, thanks for raising this! While it's possible we could adapt our installation process to fetch the raw binary and install ourselves, given that Node 4 went EOL ~3 years ago, I'm not sure that the benefits would outweigh the additional complexity. Especially since there appear to be versions in the Node v4 channel that _do_ include the zip file.

We can definitely improve the error message, however, to detect that the requested version is older and not supported.
