### ISSUE TITLE
Bot Framework Composer unable to detect installed NodeJS

### ISSUE THREAD

**Issue by ryub3n** [volta-cli/volta#1166]
OS: Windows 11
Bot Framework Composer: 2.1.2
Volta: 1.0.5
NodeJS: 14.19.0
![image](https://user-images.githubusercontent.com/24279903/155462460-dd4ae8fd-b9ad-4663-9481-ca251a5dc902.png)

FYI: It's installed on Windows not WSL

I installed NodeJS using Volta (via winget) but Bot Framework Composer can't detect it.
`Error calling npm to fetch template. Please ensure that node and npm are installed and available on your system. Full error message: Command failed with exit code 4294963213: npm install -g --prefix C:\Users\benso\AppData\Roaming\BotFrameworkComposer\.yo-repository --loglevel error --no-optional @microsoft/generator-bot-empty@1.2.2`

I thought this could be a problem with Composer but then I used [NVS](https://github.com/jasongin/nvs) and it worked fine.

**Comment by charlespierce** [comment]
Hi @ryub3n, sorry you're running into that! I'm not familiar with Bot Composer, but from the error I suspect that this is a conflict between Volta's interception of global installs and the underlying re-use of a global install with `--prefix` that Bot Composer is attempting to do.

If that's the case, a short-term workaround would be to set the environment variable `VOLTA_UNSAFE_GLOBAL` to `1` for that command, which will disable Volta's interception and use the normal process (which is what we want, since this is already handling the install location).

Longer-term, we may be able to improve the interception so it's smart enough to know not to bother when there's a `--prefix` flag on the command line.

**Comment by ryub3n** [comment]
@charlespierce - Thank you, I'll try the workaround.
The app is [Bot Framework Composer](https://docs.microsoft.com/en-us/composer/introduction?tabs=v2x) by Microsoft.
