### ISSUE TITLE
Using Volta and `nvm` side by side

### ISSUE THREAD

**Issue by svenjacobs** [volta-cli/volta#1176]
I recently discovered Volta and I really like it 👍🏼 Its speed when "switching" Node versions compared to `nvm` is impressive. Great work! 🥇 However I still have a few Node projects that use `nvm` which I can't migrate all at once.

Is it possible to use Volta and `nvm` side by side? Won't they interfere with `PATH` environment variables etc? Has anyone managed to solve this problem, possibly by writing a thin wrapper script that either uses Volta or `nvm` based on the current project?

I'm using macOS 12.2.1.

**Comment by charlespierce** [comment]
Hi @svenjacobs, thanks for the question! Volta is designed so that if it isn't able to determine a Node version, then it will pass through to the rest of the system, so it should be possible to use it along-side `nvm` if set up with the following constraints:

1. Make sure that the Volta shims are first in the `PATH`, ahead of nvm (usually that means making sure Volta is loaded _after_ `nvm` in your `.zshrc` or similar)
2. Don't select a default version of Node in Volta (i.e. don't run `volta install node`)

Then, if you're in a project that uses Volta, running `node` or similar will pick up those settings and automatically use the correct version. If you're in a project that doesn't use Volta, it will delegate to the rest of the system, which should pick up the `nvm` version.

That said, I haven't tested this extensively. It's possible that commands like `nvm use` alter the ordering of entries in PATH and would supercede Volta, I'm not 100% on how those are implemented.

**Comment by ljharb** [comment]
That should work just fine. nvm tries to preserve PATH locations when you run `nvm use`.

Alternatively, nvm can go first in the PATH, and `nvm use system` would delegate to volta (this is something i have tested extensively, altho not with volta specifically).

**Comment by charlespierce** [comment]
Perfect, thanks for clarifying @ljharb!

**Comment by svenjacobs** [comment]
This sounds good, thanks for the feedback 👍🏼

**Comment by ProLoser** [comment]
I think the best approach is to run `nvm alias default system` so that `nvm` defaults to allowing volta to work.

I do not like using `nvm` side by side with volta because it messes with the node version globally and requires extra scripts to `auto nvm use` since these are atomic changes like volta does which are not atomic.

If you run `nvm use` you will need to run `nvm use system` to re-enable volta on that same terminal.

**Comment by ljharb** [comment]
@ProLoser i'm not sure what you mean by "globally" - nvm just changes `$PATH` in a single shell session. Extra scripts that inherit the PATH should work fine.

`nvm use system` is indeed what you'd do to "turn off" nvm and use whatever it was shadowing in the PATH.

**Comment by ProLoser** [comment]
@ljharb when you execute `nvm use` with anything other than `system` it will take effect across terminal instances and across all directories, so _essentially_ it kicks in on the machine globally. `volta` only kicks in when it's specified in the project.

**Comment by ljharb** [comment]
That is 1000% incorrect - unless you're maybe using nvm-windows, a different project?

nvm only works by updating the PATH, which can't ever affect other shells.

**Comment by ProLoser** [comment]
I'm on mac but I installed with homebrew

**Comment by ljharb** [comment]
nvm is very much unsupported when installed through homebrew, but I can't conceive of how that would make it system-wide. Either way, please do not ever use nvm installed any way but the install script in its readme.
