### ISSUE TITLE
Wrong node version picked up by NX

### ISSUE THREAD

**Issue by nemonemi** [volta-cli/volta#1177]
Hello,
I have just updated my node version from 14.16.0 to 16.14.0 because the NX migration warranted it.

Now, my node version is reported as 16.14.0, however, the NX still detects the previous version. 
![image](https://user-images.githubusercontent.com/77624664/157063160-32dff4b0-3d57-4dc9-89af-6be650ce7b0e.png)
```
λ nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.16.0
  OS   : win32 x64
  yarn : 3.0.2

  nx : 12.9.0
  @nrwl/angular : Not Found
  @nrwl/cli : 12.9.0
  @nrwl/cypress : 12.9.0
  @nrwl/devkit : 12.9.0
  @nrwl/eslint-plugin-nx : 12.9.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.9.0
  @nrwl/linter : 12.9.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 12.9.0
  @nrwl/schematics : 8.12.11
  @nrwl/tao : 12.9.0
  @nrwl/web : 12.9.0
  @nrwl/workspace : 12.9.0
  @nrwl/storybook : 12.9.0
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

![image](https://user-images.githubusercontent.com/77624664/157063232-2dbfebb2-3095-4509-9760-4ebf6a4e9dc4.png)

https://github.com/nrwl/nx/issues/9221

**Comment by nemonemi** [comment]
The issue is with the global NX package, not Volta.

**Comment by charlespierce** [comment]
@nemonemi Since you have `nx` installed globally, the issue you're seeing may be the pinning behavior we do for global tools. As described [in the docs](https://docs.volta.sh/advanced/packages#pinned-node-version), we pin Node for each global tool separately (and separate from your default). This ensures that your tools continue to work as expected even if Node versions change.

At the bottom of that page there's a command you can use to pick a specific version of Node for a given tool, perhaps using that would let you choose the version to run with `nx` (although since that is pinned to `nx`, it won't give meaningful results for an individual project).

**Comment by nemonemi** [comment]
@charlespierce , 
thanks for taking your time to provide a meaningful response.

>You can change that version by changing your default

How would one go about changing the default node version? That is surely not the pinned one in the package.json, or?

**Comment by charlespierce** [comment]
@nemonemi You select a default version (the one used when you're _not_ in a project that has a version pinned) using `volta install node@<version>` (You can also omit the `@<version>` to get the latest LTS release). Or, if you don't want to change the default, you can use the `volta run` command listed at the end of that page.

**Comment by nemonemi** [comment]
Got it!
Using the default option doesn't work for me, but `volta run`, e.g. `volta run --node 15 nx report` does.
