### ISSUE TITLE
Unable to run installed tools after custom windows installation

### ISSUE THREAD

**Issue by johanndev** [volta-cli/volta#1189]
### System information
```
Windows 10 20H2
```

I have a fairly locked down machine at work where I'm trying to install volta. I have both a normal user account and a privileged (admin) account.

My normal user account is only allowed to execute custom programs from a specific location - that's why I want to customize volta's install directory

I tried to follow the steps outlined [here](https://docs.volta.sh/advanced/installers) to install volta in this custom location.

### Installation steps
1. Download the latest volta release archive (`volta-1.0.6-windows.zip`)
2. Extracted the contents of the archive to `C:\Program Files\PrivilegedFolder\volta`
3. Created a new SYSTEM env var `VOLTA_HOME` with the value: `C:\Program Files\PrivilegedFolder\volta`
4. Prepend the SYSTEM path variable with `%VOLTA_HOME%` 
5. Prepend the USER path variable with `%VOLTA_HOME%\bin` 
6. Start a new powershell prompt as USER, initalize volta and install node:
	```powershell
	> volta setup
	success: Setup complete. Open a new terminal to start using Volta!
	> volta install node
	success: installed and set node@16.14.2 (with npm@8.5.0) as default
	```
7. Close the PS prompt, open a new PS prompt and try to run node - which unfortunately fails:
	```powershell
	> node -v
	node: The term 'node' is not recognized as a name of a cmdlet, function, script file, or executable program.
	Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
	```
Volta does seem to respect the `VOLTA_HOME` directory:
```powershell
> volta which node
C:\Program Files\PrivilegedFolder\volta\tools\image\node\16.14.2\node.EXE
```

Apparently I'm missing something in regard to the shim directory `%VOLTA_HOME%\bin`... Does anybody have a clue what that could be?

Thanks!

**Comment by charlespierce** [comment]
Hi @johanndev, thanks for reporting! This is a miss for our documentation around custom installs, as the Windows environment works slightly different than the Unix one. For various reasons, the Windows MSI installer actually creates the `node`, `yarn`, `npm`, etc. shims directly in the install directory as renamed copies of `volta-shim.exe`. This is separate from the symlink shims that are created for 3rd-party packages.

It looks like our documentation doesn't include that step for custom installations 🤦🏻  What you'll need to do to duplicate the MSI installer is create 4 copies of `volta-shim.exe` in the same directory, named `node.exe`, `npm.exe`, `npx.exe`, and `yarn.exe`. I'll look to get the documentation updated to reflect that for Windows.

Additionally, it appears (see #663) that some packages expect `npm`, `npx`, and `yarn` to be available with `.cmd` files. So the installer also creates very basic versions of those files, each of which has the contents below. If you're using one of those packages (the notable one is React Native), then you may also need to create `npm.cmd`, `npx.cmd`, and `yarn.cmd` with those contents in the same directory. https://github.com/volta-cli/volta/blob/5be0e1f08982cf7969a68265cf19b77482cf480c/wix/shim.cmd

There's also an outstanding issue #579 around creating a better way to handle shims, since there are all these oddities and corner cases with Windows that don't pop up on Unix. If we got something like that implemented, we could likely unify the install process, making all of this obsolete.

**Comment by johanndev** [comment]
Thanks for the detailed instructions and explanation, @charlespierce!

Everything works as expected 👍
