### ISSUE TITLE
`volta install node && node --version` on Ubuntu 18.04 is not working anymore

### ISSUE THREAD

**Issue by felipecrs** [volta-cli/volta#1371]
It used to work, now it's not working anymore. Most likely this is due some Node.js newer requirement. I wonder if Volta should do something to address it.

Reproduce:

```dockerfile
# bionic = ubuntu 18.04
FROM buildpack-deps:bionic-curl

ENV VOLTA_HOME="/usr/local/volta"
ENV PATH="${VOLTA_HOME}/bin:${PATH}"
RUN curl -fsSL https://get.volta.sh | bash
RUN volta install node
RUN node --version
```

```console
docker buildx build --progress=plain .
```

**Comment by charlespierce** [comment]
Hi @felipecrs, that's odd! It looks like it should. Do you have visibility into the error you get with that setup?

**Comment by felipecrs** [comment]
Oh yeah! I totally forgot to include it here:

```
RUN node --version:
#8 0.344 node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
```

**Comment by charlespierce** [comment]
Ahh, that helps, thanks! I believe that issue is with Node compatibility: The latest version of Node (which is what is installed when you run `volta install node` without a version specifier) appears to require a version of glibc which is newer than what comes by default with Ubuntu 18.04. I suspect you'd see that issue as well trying to install the same Node version directly, without Volta.

You can work around it in this case by adding a version specifier (e.g. `volta install node@16`) to limit it to a version that is known to work with that version of Ubuntu.

Unfortunately, I don't think there's a clear way that Volta could detect those kinds of binary compatibility issues at install time to provide a better message 🙁

**Comment by felipecrs** [comment]
Fair enough, since even the native distribution seems to be broken:

https://github.com/nodesource/distributions/issues/1402
