### ISSUE TITLE
Can't install tools behind corporate proxy

### ISSUE THREAD

**Issue by rcsilva83** [volta-cli/volta#1376]
I'm getting an error while installing yarn because it is trying to access "https://classic.yarnpkg.com/latest-version" bypassing the corporate proxy. Does Volta supports HTTP proxy configuration?

**Comment by Purexo** [comment]
Fixed by https://github.com/volta-cli/volta/pull/1375, I just test it.
Need to wait the next release now.

**Comment by rcsilva83** [comment]
Great news, @Purexo! I have 2 questions:

1. Is there any ETA for this release?
2. Will it use the OS proxy configuration? It is Windows, in my case.

**Comment by Purexo** [comment]
By "OS proxy configuration" with windows, you mean Settings / Network / Proxy ?

My enterprise do not use this anymore but hook directly on network card with a virtual one (Cisco AnyConnect) so I cannot test proxy part, the only thing I need is software support OS CA Store, else TLS all TLS connection are rejected because certificate is not trusted.

Volta rely on attohttpc http client : https://github.com/sbstp/attohttpc#current-feature-set wich support HTTP Proxy
You can try `HTTP_PROXY` / `HTTPS_PROXY` env variable.

I don't know if attohttpc is supposed to support OS Proxy configuration, I let you search issues in their repo and ask for it if no issue on this topic.

Best regards

**Comment by rcsilva83** [comment]
Thanks, @Purexo, the env variables worked. However, my enterprise uses an auto config script for proxy configuration, so it might not be so simple to configure correctly these variables system wide. So, in this case, it would be very useful if Volta had a specific proxy configuration, much like `npm` itself has.

Maybe I should close this issue and open a feature request, right?

**Comment by charlespierce** [comment]
@rcsilva83 I don't think you need to close and re-open, this issue can serve as the feature request! I'm not sure what all goes into detecting / using the OS proxy settings, we can look into making a request / PR to attohttpc to add that behavior, however. For Volta-specific configuration, we do have the [Hooks mechanism](https://docs.volta.sh/advanced/hooks) to set custom locations from which to fetch. However it definitely has some rough edges and may not easily serve your needs (updating the Hooks to be more easily usable is one of the things we'd love to get to with enough time 😄)

**Comment by rcsilva83** [comment]
Yes, I'm using the hooks mechanism to configure all our internal mirrors for NodeJS, npm and Yarn. But I need the Internet connection for yarn/latest (set as "https://classic.yarnpkg.com/") and that's where I was having some issues.

**Comment by rcsilva83** [comment]
@charlespierce , sorry but I opened a new issue because I feel this one was already solved by Purexo's comment and I think it would be confusing to discuss the idea of having a Volta specific proxy configuration here.

Thanks for your attention and I think we can continue discussing this idea on #1398 .
