### ISSUE TITLE
Can't run globally installed node modules

### ISSUE THREAD

**Issue by Ali-Hussein-dev** [volta-cli/volta#1400]
After I uninstalled Volta, I am not able to run any globally installed node modules on my device. 
window 11
Node 16.17.0

**Comment by Ali-Hussein-dev** [comment]
here is an error message example when I run `sanity init`
![error](https://user-images.githubusercontent.com/42802922/206437578-f726415d-7793-4063-af80-0c696c70cbbc.jpg)

**Comment by charlespierce** [comment]
Hi @Ali-Hussein-dev, sorry about that! It looks like the uninstall process isn't very robust (it's tricky to get the MSI file to completely clean things up). To fix that, you'll need to update your `Path` environment variable to remove the `C:\Users\alilo\AppData\Local\Volta\bin` directory (which will remove the now-broken Volta shims from being called). A slightly easier (though less robust) approach would be to remove the `%LOCALAPPDATA%\Volta` directory entirely, which will also prevent those shims from trying to run (since they won't exist any more!). For a complete removal, you would want to do both of those things.
