### ISSUE TITLE
Cannot uninstall yarn

### ISSUE THREAD

**Issue by ontoneio** [volta-cli/volta#1431]
I was needing yarn right quick for a project inspection and then I was going to uninstall.
To my surprise I was met with this message from volta. 
`error: Uninstalling yarn is not supported yet.`

Hopefully this isn't intentional. 🥲 

Thanks!

**Comment by charlespierce** [comment]
Hi @ontoneio, for the special-cased tools like `npm`, `node`, and `yarn`, with Volta's model, the action `uninstall` is actually poorly named. It's probably closer to clearing a cache, since Volta will always re-download a tool if it's needed. Due to that, we haven't yet implemented the cache cleaning operation. We do have an issue tracking this already: #330 

Please track issue for updates!

**Comment by fev4** [comment]
Ran into this as well!
Even when I remove the image folder dedicated to yarn it manages to come back when running `yarn --version`.

**Comment by alissawix** [comment]
so, if I have volta there is no way that I can remove yarn from my computer without removing volta?
basically all I need is to remove yarn from the Path
