### ISSUE TITLE
Binary are missing within a terminal after upgrading from 1.1.0 to 1.1.1

### ISSUE THREAD

**Issue by kuncevic** [volta-cli/volta#1432]
I have a volta installed using brew.

The thing is that I've just upgraded to the latest volta.

In result all previously installed binaries are no longer available in terminal.
However `volta list` still listing all of them

```
➤ volta list
⚡️ Currently active tools:

    Node: v18.12.0 (default)
    Yarn: v1.22.19 (default)
    Tool binaries available:
        nest (default)
        vc, vercel (default)
```
So none of it is available in my terminal
<img width="290" alt="Screenshot 2023-01-27 at 16 14 58" src="https://user-images.githubusercontent.com/1283734/215014745-fef2e628-7dcb-4e76-b57b-82372bae1bd9.png">

Here is my `.vola/bin` folder
<img width="499" alt="Screenshot 2023-01-27 at 16 17 00" src="https://user-images.githubusercontent.com/1283734/215014773-85ec366c-55b3-4c9f-be71-243905865133.png">

`$path`

`/opt/homebrew/opt/util-linux/bin /Users/user/.volta/bin /opt/homebrew/sbin /opt/homebrew/bin /usr/local/bin /System/Cryptexes/App/usr/bin /usr/bin /bin /usr/sbin /sbin
`
Other:

```
➤ volta -v
1.1.1
```

```
➤ brew info fish
==> fish: stable 3.6.0 (bottled), HEAD
User-friendly command-line shell for UNIX-like operating systems
https://fishshell.com
/opt/homebrew/Cellar/fish/3.6.0 (1,475 files, 15.4MB) *
  Poured from bottle on 2023-01-08 at 22:47:23
```

**Comment by charlespierce** [comment]
Hi @kuncevic, sorry you're running into this! I believe the underlying issue is this one: https://github.com/volta-cli/volta/issues/927

There's still some open issues to get things working to run the appropriate cleanup steps in brew. As a one-off, you should be able to run `volta-migrate` to regenerate the shims, so that they point to the appropriate location, which should get everything working again.

If that doesn't resolve it, please re-open and we'll dig in to figure out what else is going on.

**Comment by kuncevic** [comment]
@charlespierce yeah i c, `volta-migrate` magically solved the problem. 
Looking forward #927 to be resolved soon.
