### ISSUE TITLE
Suggestion: need a new command called `volta use` to switch default node version

### ISSUE THREAD

**Issue by Gorvey** [volta-cli/volta#1455]
When I use `volta install node@version` to switch the default node version. I find it a bit strange, Because I was use  `nvm`  before.

So I think `volta use node@version` is more semantic.

**Comment by vela666** [comment]
good advice.

**Comment by chriskrycho** [comment]
Thanks for the suggestion! There's been some previous discussion of things in this basic space:

- https://github.com/volta-cli/volta/issues/994
- https://github.com/volta-cli/rfcs/issues/41

Since we already have #994 tracking the overarching suggestion in this repo, I'm going to go ahead and close this and move further discussion over there.
