### ISSUE TITLE
Volta: How to read from existing package.json pinned version

### ISSUE THREAD

**Issue by abhishek1nair** [volta-cli/volta#1498]
Need support for understanding how Volta works with a project where versions are already pinned in the package.json. I read through the documentation but couldn't figure out how this exactly work. I have project that has the following in their package json:

```
"volta": {
    "node": "16.15.0",
    "yarn": "1.22.10",
    "extends": "<some file to extends>"
  },
```

And my personal env has the following versions of these:
```
$ node -v 
v18.14.2

$ yarn -v
1.22.19
```

I assumed that if I run `volta run` it should pick up the version and install the right version in the directory, but this doesn't happen. 
Based on the documentation then I used:
```
$ volta pin yarn@1.22.10
$ volta pin node@16.15.0
```
to set the version, but even then when I run the `node -v` or `yarn -v` command I see that same version as my local setup.

Only thing that works is using `volta run yarn -v`, this returns the right version. Please advice what is the right way of using volta in an existing project.

**Comment by chriskrycho** [comment]
The basic way that Volta works is: if you use `volta run` it will use the specified version; otherwise it will use the version you have pinned if you are in a project with a pinned version; otherwise, it will use the default/user-level installation. `volta run` is not related to pinning versions; it is a way of *overriding* the tool that would otherwise be used. You don't need to do anything in particular to get the right version when you have a pinned version; Volta will use it automatically.

If you are not seeing those versions, you should check what your `PATH` has; it sounds like you are actually just not getting the Volta-managed version at all.

I am closing this, but feel free to ask further questions!
