### ISSUE TITLE
why volta invoke  npm install will cost so much cpu? 

### ISSUE THREAD

**Issue by yinsang** [volta-cli/volta#1519]
Could someone told me how to deal with this problem?
It will make my Mac too Kakaka to work.
![image](https://github.com/volta-cli/volta/assets/12373328/767293fc-35ce-4e31-ab82-250d9ae249d5)

**Comment by yinsang** [comment]
```
rm -rf /Users/XXXXXXXUSERXXX/Library/Caches/typescript
```
helps me

**Comment by chriskrycho** [comment]
Very likely that's a general `npm install` issue, as once Volta handles which version of `npm` to use and the target directory to install into, it gets completely out of the way. Since busting the cache also helped, I'd guess there may have been a bug in some specific version of npm, but that is just a wild guess! Closing this as it seems unrelated to Volta.
