### ISSUE TITLE
Setting the nodejs version number

### ISSUE THREAD

**Issue by xiaoLangtou** [volta-cli/volta#1536]
Use the command  `volta pin node@16` to add this to the file `package.json`
`{volta':{'node':'16.19.1'}} ` Does the node version here support fuzzy definition, set to a form greater than or equal to

**Comment by chriskrycho** [comment]
Hi @xiaoLangtou – sorry about the delay; we've all been super busy lately. We intentionally do *not* support fuzzy versions like that, because Volta's philosophy is to give 100% reproducible version selection. You can think of the version set in the `Volta` key in `package.json` as being something like the versions in your lock file: if you do `pnpm install some-package@1`, your lock file will end up with a specific version, and it won't change unless you actively change it. We do the same thing here! That way everyone on your team (and, if you use Volta for your CI, those jobs, too) ends up with the same version. We describe this briefly in the docs [here](https://docs.volta.sh/guide/understanding#pinning-node-engines).
