### ISSUE TITLE
Target `.zshenv` over `.zshrc`

### ISSUE THREAD

**Issue by Fyko** [volta-cli/volta#1537]
Is there any specific reason why Volta adds her variables to `.zshrc` and not `.zshenv`? Seems a bit more apt.

I could PR if there is conseus.

**Comment by chriskrycho** [comment]
Hi @carterhimmel – sorry for the delay, and thanks for the suggestion. I've been out of the `.zsh` world for quite a while; can you link to docs indicating when each should be used? I think we'd be open to a PR, though we would likely want to continue to have the fallback behavior to use `.zshrc` if the other isn't present (that's how all of those work at present, if I recall correctly).

**Comment by carterhimmel** [comment]
Sure thing! https://zsh.sourceforge.io/Intro/intro_3.htm
> `.zshenv` is sourced on all invocations of the shell, unless the -f option is set. It should contain commands to set the command search path, plus other important environment variables. `.zshenv` should not contain commands that produce output or assume the shell is attached to a tty.

> `.zshrc` is sourced in interactive shells. It should contain commands to set up aliases, functions, options, key bindings, etc.

**Comment by chriskrycho** [comment]
Totally missed the follow-up from @Fyko – looks perfectly reasonable. Since it should only affect new users/setups and existing `.zshrc`-based configs will work fine, we need to flag this in release notes but in my view it's not *breaking*. (I welcome input from @rwjblue and @charlespierce to the contrary, thought!) Go for it, @gautamprikshit1!
