### ISSUE TITLE
how to force yarn instead of npm?

### ISSUE THREAD

**Issue by lorenzofranzone** [volta-cli/volta#1550]
Hi! In my package.json I've set:
```
"volta": {
    "node": "18.17.1",
    "yarn": "4.0.0-rc.51"
  }
```
now if I try node-v in my project I get the version set in my volta portion of code, if I try out of my project I get another version. right.

But now if I need to install a package or run a script, I would like to force my project using yarn, but if I use npm install ... I create a package.lock instead of a yarn.lock. Maybe I still haven't figured out how to use volta to establish the default package manager.
Thanks for your time.

**Comment by chriskrycho** [comment]
Hi @lorenzofranzone – Volta is not designed to force people to use a specific package manager, but rather to make sure that whatever package manager your project is using, developers will get the same version of! We also don't intend to *add* that behavior, because people might have good reasons for using a different package manager (e.g. testing out whether they have different behavior in certain conditions, they don't care about being on the same package manager because they're not intending to do a PR, only to test something out, etc.). Hope that clarifies things a bit!

**Comment by lorenzofranzone** [comment]
Hi @chriskrycho, thank you very much, now it's all clear ;)
