### ISSUE TITLE
Аdd the feature to add global packages

### ISSUE THREAD

**Issue by 020AlievIB** [volta-cli/volta#1555]
Can Volta add global packages and install them when opening a project?

I get this when try to pin global package 

error: Only node and yarn can be pinned in a projec

Use `npm install` or `yarn add` to select a version of package_name for this project.

**Comment by chriskrycho** [comment]
@020AlievIB Volta will not automatically install global tools when entering a package, no. Among other things, that would be a pretty serious security vulnerability, as combined with post-install hooks it would mean that just entering a project could perform arbitrary operations on your system.

You can, however, install default (global) versions of packages with `volta install` or the package manager global installation commands, and those will be globally available on your system. If you have a default version installed and then enter a directory which has that same tool installed via `dependencies` or `devDependencies`, Volta will make sure that invoking it uses the version installed in the package instead of the default/global version. But that means that for per-package versions, you will want to just use normal package dependencies! For more, see [the Understanding Volta section](https://docs.volta.sh/guide/understanding) in [the docs](https://volta.sh).
