### ISSUE TITLE
Why does Volta add TypeScript to my package-lock?

### ISSUE THREAD

**Issue by TheJaredWilcurt** [volta-cli/volta#1560]
I updated all dependencies in my repo. Then did a commit. Then uninstalled `nvm-windows`, rebooted, and installed Volta.

I added this to the `package.json` (to match what I had previously)

```json
  "volta": {
    "node": "18.14.0",
    "npm": "9.3.1"
  },
```

Then ran `npm install` and it added this to the package-lock:

![package-lock diff with TS entry](https://github.com/volta-cli/volta/assets/4629794/564d11d8-8116-4258-bda5-83a8cfe97a0e)

Why is Volta adding TypeScript to my package lock? Can I turn that off. I don't see how a version manager should affect the package lock.

**Comment by charlespierce** [comment]
Hi @TheJaredWilcurt, that's very odd. Volta absolutely does not add anything to `package.lock`, in fact it doesn't every change anything with the JS dependencies. The only thing it does to interact with `dependencies` in `package.json` is to read the values in order to detect local versions of tools.

Is it possible that you updated dependencies without doing an install and so `package.lock` wasn't updated by the dependency update, so it only got changed after you committed?

**Comment by TheJaredWilcurt** [comment]
My bad. I tried it on some other repos and it only updated the package-lock in this one. I don't know why `npm install` didn't add this sub-sub-sub-sub dependency the first time. But after switching to Volta and re-running it, it did. And [it is needed apparently](https://github.com/nwutils/create-desktop-shortcuts/actions/runs/6606741652/job/17943267708#step:5:9).

Sorry for false alarm. Gonna be showing Volta off at work today and we will likely start adopting it on several teams 👍
