### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by JamesHenry** [volta-cli/volta#1577]
Hi Folks,

I'm a **huge** fan of volta, and I've evangelized it to countless projects over the last couple of years.

Things seem to be very quiet on the repo these days in terms of releases and maintainer responses, however.  I remember it originally being backed by LinkedIn, is that no longer the case?

Please could you share the status and outlook of the project?

Many thanks!

**Comment by rdsedmundo** [comment]
I will move back to `nvm` or consider `fnm` which is also written in Rust, unfortunately. Had tons of issues upgrading to Node.js 20 (seeing "could not unpack..."), and now that I have finally managed to do it, I upgraded `Volta` itself and noticed all its aliases still pointing to the old version 1.0.5 I had (`$VOLTA_HOME/bin/node -> /Users/work/homebrew/Cellar/volta/1.0.5/bin/volta-shim`—I'm in 1.1.1).

**Comment by batusai513** [comment]
you can also try https://moonrepo.dev/proto

**Comment by chriskrycho** [comment]
@JamesHenry thanks for the ping – I think it’s a valid question given the low activity level! LinkedIn is not currently *actively* funding work on it, but we maintainers (whether still at LinkedIn or otherwise) are aware that it is unfortunate for the project to be languishing. I have reached out to the core maintainer group and we will see what kind of improvements we can make on the maintenance story here!

(Perhaps this is obvious, but I think it is worth saying explicitly: if and as other folks are interested in helping maintain this, we are *very* open to that!)

**Comment by chriskrycho** [comment]
I should clarify: LinkedIn still very actively uses it and in that sense “backs” it, but as of when I left LinkedIn a couple months ago, it has for several years now largely been in the state where it does everything LinkedIn needs so well that most developers don't notice or think about it… which is great, but also means it is hard to make a business case for investing further in it at LinkedIn!

**Comment by chriskrycho** [comment]
We actually got a bunch of folks who have helped build and maintain this over the years together this afternoon and put together a bit of a strategy to get momentum going again! We're going to *try* to see if we can get various bugs fixed, a couple features (e.g. full pnpm support, `.node-version` inter-op, etc.) implemented, etc. We will also be scheduling monthly calls, open to anyone, to sync up on it, find ways to contribute, etc., which will be announced in [the Discord](https://discord.gg/hgPTz9A).

Thanks for the frank question—it was helpful for getting me to kickstart that and for us to get the ball rolling on this. Going to close this with that, but hopefully you'll see more movement here in the months ahead!
