### ISSUE TITLE
publish in homebrew

### ISSUE THREAD

**Issue by dherman** [volta-cli/volta#16]
We should publish Mac installers as formulae in homebrew.

**Comment by twokul** [comment]
I feel like I got the formula to a decent place and we can start talking about it.

Spoiler: I'm new to Rust/Cargo and how the build system works don't yell at me for doing silly things 😬 

## Name

There is already a cask package called "notion", see [here](https://www.notion.so/). I'd say we can name ours `notion-cli`, or we can keep it as `notion` (since cask packages and regular ones have different registries).

I personally would go with `notion-cli`, but I'd love your thoughts @dherman.

## Homebrew formula

The formula itself (snippet below) gets generated automatically by running:

```sh
brew create https://dl.dropboxusercontent.com/s/rawxzfb4fsruu14/notion-cli-0.1.0.tgz
```

Properties and methods like `desc`, `homepage`, `depends_on`, `install` and `test` were added by me. File name has to contain `0.1.0` so we don't specify it in the formula itself via `version` property.

I hacked together a `notion-cli` archive just to get started, it contains:

```sh
$ tree -L 1 homebrew
homebrew
├── Cargo.lock
├── Cargo.toml
├── build.sh
├── crates
├── install.sh
├── install.sh.in
└── src
```

Once the folder is downloaded, we run `cargo build` and then `build` and `install` scripts. From then on, `notion` should be available and good to go.

Also, I believe we can remove [the code from `install.sh.in`](https://github.com/notion-cli/notion/blob/master/support/unix/install.sh.in#L176) which adds `notion` binary to the `PATH` and replace it with [`bin.install`](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#bininstall-foo) in the recipe.

```ruby

class NotionCli < Formula
  desc "The hassle-free node.js manager"
  homepage "https://github.com/notion-cli/notion"
  url "https://dl.dropboxusercontent.com/s/rawxzfb4fsruu14/notion-cli-0.1.0.tgz"
  sha256 "90f96b6c7e33593acb0dfb6917461e9dbc095f4c71bf6ea06a75b06638f4aa18"

  depends_on "rust" => :build

  def install
    system "cargo", "build", "--release"
    system "./build.sh",
           "./target/release/notion",
           "./target/release/node",
           "./target/release/launchbin",
           "./target/release/launchscript"
    system "./install.sh"
  end

  test do
    assert_equal "The hassle-free node.js manager", (system "notion -V")
  end
end
```

## Audit

Homebrew documentation suggest we run [`brew audit`](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#audit-the-formula) command on a newly generated formula to make sure we adhere to their standards.

Audit showed that we are not notable enough yet:

```sh
$ brew audit --new-formula notion-cli
notion-cli:
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
Error: 1 problem in 1 formula
```

I'm not sure what to do about the above yet, let's discuss.

**Comment by claydiffrient** [comment]
Has anyone circled back to this?  It'd be cool to get this in now since it appears that the repo is notable enough now.

**Comment by alizain** [comment]
@dherman now that this project has been renamed to `volta`, any plans on adding a homebrew formula?

**Comment by cowboy** [comment]
@dherman is there anything the project needs to help make this happen?

**Comment by filipekiss** [comment]
I've created a simple formula that might be a good starting point. It's available [here](https://github.com/filipekiss/homebrew-volta).

The formula does not build from source but uses the tar. I wanted to make sure the installation was as close to using `curl https://get.volta.sh | bash`. The only thing the Formula doesn't do currently is running `volta setup` but that could be updated to be the default and an option to `--skip-setup` could be added to the formula.

Let me know what you guys think :)

**Comment by filipekiss** [comment]
While working on the formula for Homebrew I've encountered an issue and I'm not sure if I should file this as a separate bug, but the installation script from `brew` is not able to run `volta setup`:

```
error: Could not locate user profile.
Tried $PROFILE (), ~/.bashrc, ~/.bash_profile, ~/.zshrc, ~/.profile, and ~/.config/fish/config.fish

Please create one of these and try again; or you can edit your profile manually to add '/Users/filipekiss/.volta/bin' to your PATH
```

Running `volta setup` as soon as the installation is finished the command works as instended.

I think this has something to do with [Homebrew's superenv](https://docs.brew.sh/Formula-Cookbook#superenv-notes) so I'm not sure if it's worthing pursuing this.

**Comment by filipekiss** [comment]
Anyone who has access to a macOS Catalina can try to [help me debug the formula](https://github.com/Homebrew/homebrew-core/pull/51052)? I'm getting an error when building to Catalina during the CI step for the pull-request and I'm not able to figure out how to deal with it since I don't have access to Catalina…

**Comment by charlespierce** [comment]
It looks like this was completed some time ago thanks to @filipekiss!
