### ISSUE TITLE
volta pin node giving v20.10.0 when v20.11.0 is released

### ISSUE THREAD

**Issue by broksonic21** [volta-cli/volta#1640]
Per [https://github.com/nodejs/node/issues/51423](https://github.com/nodejs/node/issues/51423) and [https://github.com/nodejs/node/releases/tag/v20.11.0](https://github.com/nodejs/node/releases/tag/v20.11.0), v20.11.0 is released

`volta run --node 20.11.0 node -p process.version` works to get 20.11.0, but `volta pin node` is returning 20.10.0 only

```
volta pin node
success: pinned node@20.10.0 in package.json
```

**Comment by chriskrycho** [comment]
Per the thread at https://github.com/nodejs/node/issues/51423 it looks like this is probably a caching issue upstream rather than a Volta issue, and should resolve itself relatively shortly (it already correctly works on my machine when I test it). Closing this accordingly; thanks for reporting and doing the digging to see the upstream issue!
