### ISSUE TITLE
When trying to install new versions volta hangs indefinitely and blocks all other network requests from resolving

### ISSUE THREAD

**Issue by effervescentia** [volta-cli/volta#1744]
Websites will not load and I have not waited long enough for the command to ever resolve or error (I've waited over 10 minutes)

I was able to solve this temporarily for `node` downloads by configuring the `hooks.json` file with a mirror

```json
{
    "node": {
        "index": {
            "template": "https://mirrors.dotsrc.org/nodejs/release/index.json"
        },
        "distro": {
            "template": "https://mirrors.dotsrc.org/nodejs/release/v{{version}}/{{filename}}"
        }
    }
}
```

this is also happening when trying to install new versions of `yarn`
I first encountered this close to 2 or 3 weeks ago and it has not yet been resolved
it doesn't looks like a new version of `volta` has been released, but perhaps some certificates have expired?

if I open Activity Monitor and quit `volta-shim` my website loads immediately

**OS**: MacOS 14.4.1

**Comment by effervescentia** [comment]
as a follow up I wasn't able to find a relevant mirror for `yarn` but I followed [this comment](https://github.com/volta-cli/volta/issues/651#issuecomment-818927941) and used the releases from github as distro template

```json
{
    "node": {
        "index": {
            "template": "https://mirrors.dotsrc.org/nodejs/release/index.json"
        },
        "distro": {
            "template": "https://mirrors.dotsrc.org/nodejs/release/v{{version}}/{{filename}}"
        }
    },
    "yarn": {
        "distro": {
            "template": "https://raw.githubusercontent.com/yarnpkg/berry/%40yarnpkg/cli/{{version}}/packages/yarnpkg-cli/bin/yarn.js"
        }
    }
}
```

**Comment by xavidop** [comment]
this happens to me as well!

**Comment by edison-vflow** [comment]
I am also experiencing this issue
@Volta could you please help resolve

**Comment by charlespierce** [comment]
This is extremely odd, thank you all for reporting! Is this still happening and consistent? And does it happen trying to access the paths directly via `curl` or the browser (e.g. `https://nodejs.org/dist/index.json`)?

**Comment by gillyb** [comment]
Happening to me too..  
Trying to reach that url from the browser works for me.

**Comment by effervescentia** [comment]
this is definitely still happening, and I don't have any issues curling that URL
It's also happening with `yarn` releases, so nothing specific to the NodeJS download servers

**Comment by effervescentia** [comment]
@charlespierce anything else I can do to help find the source of the issue?

**Comment by JamesPHoughton** [comment]
I'm seeing this too, using volta 1.1.1 on macOS 14.5, the verbose output is:
```bash
volta install node --verbose              
[verbose] No custom hooks found
[verbose] Found valid cache of Node version index
[verbose] Found newest LTS node version (20.14.0) from https://nodejs.org/dist/index.json
[verbose] Acquiring lock on Volta directory: /Users/me/.volta/volta.lock
[verbose] Downloading node@20.14.0 from https://nodejs.org/dist/v20.14.0/node-v20.14.0-darwin-arm64.tar.gz
```
This is all that is output before the process hangs. 

There doesn't seem to be excessive CPU usage:
```
...% top -stats pid,command,cpu | grep -i volta
26382  volta            0.0 
26382  volta            0.0 
29336  volta            0.0 
29336  volta            19.3
29336  volta            0.1 
29336  volta            0.0 
29336  volta            0.0 
29336  volta            0.0 
```
And network traffic is pretty constrained - `nettop` doesn't show any existing outbound connections

```
...% nettop | grep -i volta
                                                                                     interface         state        bytes_in       bytes_out   rx_dupe    rx_ooo     re-tx   rtt_avg   rcvsize    tx_win  tc_class    tc_mgt   cc_algo P C R W arch
volta.30865                                                                                                          675 KiB        1033 B      21 KiB     0 B       0 B
   tcp4 127.0.0.1:55871<->localhost:10011                                                  lo0   Established         675 KiB         656 B      21 KiB     0 B       0 B     1.22 ms   630 KiB   398 KiB        BE         -     cubic - - - -   so
   tcp4 127.0.0.1:55873<->localhost:10011                                                  lo0   Established           0 B           377 B       0 B       0 B       0 B     1.22 ms   398 KiB   398 KiB        BE         -     cubic - - - -   so

```

**Comment by DecathectZero** [comment]
still getting this behavior, bump

**Comment by effervescentia** [comment]
@charlespierce is there anything we can do to help you look into this? It's pretty disruptive to our development since it hangs forever without an error message and kills network traffic

**Comment by chriskrycho** [comment]
Sorry, just saw this (have been busy on other stuff!). From the error messages @JamesPHoughton shared and the description of what people are seeing, it *looks* like that’s probably coming from some interaction between a bad download and attempting to unpack the result of that.

For others on the Volta team who are spelunking/debugging (or users who want to help), the relevant chunks of code are:

https://github.com/volta-cli/volta/blob/fd9cc3fcf4db08097709e3f2be207be12f2453f2/crates/volta-core/src/tool/node/fetch.rs#L180-L184

https://github.com/volta-cli/volta/blob/fd9cc3fcf4db08097709e3f2be207be12f2453f2/crates/volta-core/src/tool/node/fetch.rs#L67-L72

https://github.com/volta-cli/volta/blob/fd9cc3fcf4db08097709e3f2be207be12f2453f2/crates/volta-core/src/tool/node/fetch.rs#L104-L111

The relevant code paths haven’t been touched in 5 years (there are a couple Clippy fixes that are unreleased, but that’s it).

I *suspect* something is happening upstream in `archive`, given that Volta prints a debug message *right before* calling `archive::fetch_native`, you all see a very long timeout, and then the next thing that happens after that very long delay is attempting to unpack the  resulting archive. Next step would be to go see whether there is an upstream issue about it, and if so if there is a fix! I will keep spelunking if and as I have time, but also welcome other folks digging in a bit.

**Comment by chriskrycho** [comment]
For anyone following on the thread, and per my edit (which you would not have gotten notified about), this is all in our own code; there is no upstream. 🤦🏻‍♂️

![8vv9b5](https://github.com/volta-cli/volta/assets/2403023/aa51fdd0-8f64-43be-9124-144559291790)

A good next step might be for us to get a build up that folks can run to diagnose, with some additional tracing in [Volta’s internal `archive` crate](https://github.com/volta-cli/volta/tree/main/crates/archive).

**Comment by chriskrycho** [comment]
Request for more info from folks on the thread who are hitting this: what operating system are you using? We have at least one confirmed Mac user, but I’d like to know for the rest as part of debugging!

**Comment by effervescentia** [comment]
> Request for more info from folks on the thread who are hitting this: what operating system are you using? We have at least one confirmed Mac user, but I’d like to know for the rest as part of debugging!

I can confirm that most (but not all) of the other folks that have been commenting / interacting with this PR are all on M1 / M2 MacBook Pros since they work with me at [Voiceflow](https://github.com/voiceflow)

**Comment by BitForger** [comment]
I have an M2 Pro MBP on Sonoma 14.5 and am experiencing this...
Interestingly enough as early as a few weeks ago, my work MBP, a M1 Max also on Sonoma 14.5 wasn't having this issue

**Comment by chriskrycho** [comment]
Hey all, I just pushed up a branch and draft PR at #1784, which you should be able to check out and build, and then use locally. The testing workflow I would recommend:

```sh
git clone https://github.com/volta-cli/volta.git
cd volta
git switch chriskrycho/debug-1744
cargo build --release
mv $HOME/.volta/bin/volta $HOME/.volta/bin/volta-backup
cp ./target/release/volta $HOME/.volta/bin/volta
volta --verbose --very-verbose
```

That final line should print the normal help output *preceded* by this line:

```
[very verbose] log level: VeryVerbose
```

(If you have a non-standard installation location, you will want to figure out where it is with `which volta` and do the same basic thing for the final two steps, but with the appropriate directory changes.)

Once you have that set up, you should be able to get much more info about where in the archive/unpacking process things are going wrong. It still may not be enough, but it should at least be a start, and I don’t know what to try next until we get this much sorted.

**Comment by effervescentia** [comment]
@chriskrycho here's the output with the debug version when installing `yarn`

<img width="1151" alt="Screenshot 2024-07-10 at 10 18 09" src="https://github.com/volta-cli/volta/assets/3784470/b3432e71-16bf-49b7-a3bb-177b14f4ecf5">

and here's the output from installing `node`

<img width="1194" alt="Screenshot 2024-07-10 at 10 27 34" src="https://github.com/volta-cli/volta/assets/3784470/6db5ed02-796c-4681-a9e1-fe650d13c8e9">

**Comment by effervescentia** [comment]
> Also, for reference, if you could copy and paste the actual text into a code snippet rather than screenshotting in cases like this

absolutely, sorry bad habit 😅

**Comment by effervescentia** [comment]
> Since it’s truncated, I assume that's where it hangs?

Correct, it hangs there with no other output indefinitely

**Comment by chriskrycho** [comment]
Okay, I have done some more debugging locally and… I need to figure out what I need to change so that `trace!` prints from *all* crates, not just the *core* crate. The reason you’re not seeing further useful log info is because the way I set things up in #1784 *only* configured the root crate, not all the other crates within Volta’s source tree, so it’s only printing debug messages. I will update here once I have that sorted!

**Comment by chriskrycho** [comment]
All right, folks, I have pushed an update to #1784 which makes the tracing I added *actually work*. We had a nice little prefix check to filter even trace-level logs down to Volta-only tracing, and that was accidentally filtering out even the internal crates in question. Whoops! You should now be able to follow exactly the same steps as above, and see something more useful and informative for us!

**Comment by effervescentia** [comment]
@chriskrycho here's the output from a `node` install

```
volta --verbose --very-verbose install node@20.13.0
[very verbose] log level: VeryVerbose
[verbose] Loaded custom hooks file: /Users/benteichman/.volta/hooks.json
[verbose] Acquiring lock on Volta directory: /Users/benteichman/.volta/volta.lock
[verbose] Downloading node@20.13.0 from https://nodejs.org/dist/v20.13.0/node-v20.13.0-darwin-arm64.tar.gz
[very verbose] fetching tarball from https://nodejs.org/dist/v20.13.0/node-v20.13.0-darwin-arm64.tar.gz
[very verbose] detected compressed size of 41914632 for tarball
```

and from `yarn`

```
volta --verbose --very-verbose install yarn
[very verbose] log level: VeryVerbose
[verbose] Loaded custom hooks file: /Users/benteichman/.volta/hooks.json
[verbose] Found yarn@4.3.1 matching tag 'latest' from https://registry.npmjs.org/@yarnpkg/cli-dist
[verbose] Acquiring lock on Volta directory: /Users/benteichman/.volta/volta.lock
[verbose] Downloading yarn@4.3.1 from https://registry.npmjs.org/@yarnpkg/cli-dist/-/cli-dist-4.3.1.tgz
[very verbose] fetching tarball from https://registry.npmjs.org/@yarnpkg/cli-dist/-/cli-dist-4.3.1.tgz
[very verbose] detected compressed size of 988600 for tarball
```

**Comment by charlespierce** [comment]
@effervescentia Thanks for sharing that!

@chriskrycho It looks like it's hanging on the `fetch_uncompressed_size` call, which makes a second HTTP request using the `Range` headers to fetch the specific block and the end of a gzip file that encode the uncompressed size of the file. We only use the uncompressed size of the file to make the progress bar for downloads more accurate (and we aren't able to get it ahead of time for Zip files on Windows at all), so that request definitely shouldn't be a long one. I wonder if it would make sense to set a fairly short timeout (on the order of 1 second perhaps?) for that 2nd request to make sure that one way or another it finishes quickly and doesn't block the rest of the process.

Alternatively, we could probably get away with skipping the 2nd request entirely and doing some estimation of the uncompressed size based on the compressed size.

A third option, which I haven't totally worked through but might be the easiest & cleanest solution: If we attach the `ProgressRead` to the underlying HTTP Reader, rather than the `GzDecoder`, then using the _compressed_ size would be relatively accurate for the progress bar (modulo the actual decompression step for the last bits of data). This would take some testing to see how much that last step affects the accuracy, but hopefully it wouldn't be too much.

**Comment by effervescentia** [comment]
@charlespierce @chriskrycho I can confirm from testing locally that setting a timeout on the request for the uncompressed size results in the download succeeding. Would you be willing to make this initial change in the short term at the cost of an inaccurate progress bar? This is an issue my team is still regularly running into and we would appreciate a fix that allows us to resume normal use of `volta` sooner if possible. Since the code is already built to handle the uncompressed size being `None` the risk seems pretty minimal

```rust
# crates/archive/src/tarball.rs @ line 137

.timeout(Duration::from_secs(1))
``` 

I've also tested one of the queries made with `attohttpc` as a `curl` request and it resolves without issue instantly, and I don't see any bugs related to this on that library's github page

```
curl https://nodejs.org/dist/v20.13.0/node-v20.13.0-darwin-arm64.tar.gz -H 'Range: bytes=41914628-41914631'
```

which I got by debugging the request made when running this volta command

```
volta --verbose --very-verbose install node@20.13.0
```

**Comment by chriskrycho** [comment]
@effervescentia let me see if I can get a more correct fix done in the next couple days, and if not then yeah, a workaround with a timeout seems totally reasonable. If nothing else, you should feel free to fork it and use the forked version in the meantime—not in a mean “if you don’t like it, fork it and maintain it yourself!” sense but in the sense that (a) our rate of change is pretty slow right now, and we haven’t changed that code in something like five years, so it should be relatively low risk and easy to keep updated; and (b) it should be fairly straightforward to flip back once we *do* get it fixed, hopefully soon.

**Comment by chriskrycho** [comment]
@charlespierce On the one hand, changing what we’re reading or just not even bothering with it (the same way we do for Windows) could “solve” this, but I’m worried that it could just leave us in a situation where we’re doing *something* and that it will actually just be that much harder to figure out if it happens even more rarely.

Things we absolutely do not understand at the moment:

- What is *actually* causing the hang? It is obviously not happening to everyone, only to a subset of users, which implies (I think!) that it is not a logical bug.
- *Why* is it happening to the users it *is* happening to (and, conversely, not to you or me or anyone else)?
- Why is it using *all available network bandwidth* for at least @effervescentia’s folks—but not, or at least not obviously, @JamesPHoughton?

---

@effervescentia and others who are experiencing this, a few more follow-on questions:

1. Are you behind a VPN when you see this, or is it happening on “regular” network traffic?

2. You noted above that “most (but not all) of the other folks that have been commenting / interacting with this PR are all on M1 / M2 MacBook Pros”—what *other* hardware and operating systems are you seeing this on? (No one has yet reported anything but macOS 14.4 or 14.5.)

3. If you capture *both* of the requests made by `attohttpc::get`—the initial one for the compressed size, and then the second one for the uncompressed size via range—and make them one after another in extremely close succession, e.g. with `curl` in a shell script, does *that* trigger this?

(The motivation for both (1) and (3) is to rule out some kind of upstream rate-limiting that is a result of hitting the same URLs in quick succession from a given IP address or something like that. The motivation for (2) is to work out whether it is possibly a bug in macOS 14.4+, since we had never had it reported prior to that.)

Finally, @effervescentia, you note that it’s taking all network bandwidth—do you have data to that effect e.g. via `nettop`, or just (!) the symptom of being unable to load other websites?

---

After staring at the implementation and thinking about the unanswered questions I posted at the top, I am *actually* inclined to ship a timeout but also `warn!` or possibly `info!` on the console in the case that it happens. I will open a PR doing just that tomorrow.

**Comment by charlespierce** [comment]
One slight complication for testing the network setup is that we actually have 2 requests open at the same time: The "actual" download request is started, then we read the response headers to get the total length of the output. Then, with that request still open (we haven't started reading the raw data), we make another request to the same URL, but with the `Range` header added. We read that request in full, and only then do we actually start streaming the full data.

I'm also curious about the VPN setup, but I suspect there's something with those two requests for the same resource that is part of the root cause.

**Comment by chriskrycho** [comment]
Yeah, that is my guess as well, but since it is not causing a problem for most users I suspect that is only part of the story. One thing we could do is reproduce just exactly that behavior in an isolated binary, enable maximum tracing with an of the shelf logger, and see if folks who are seeing this can reproduce with that. (I will put up a version of this in a bit if I get a chance.)

**Comment by chriskrycho** [comment]
Here’s what I *think* is an actual minimal reproduction of *all* the pieces we do in Volta for this particular set of network calls: https://github.com/chriskrycho/volta-networking-repro

The instructions there *should* be enough for people to see if that is sufficient to reproduce this issue. 🤞🏼 At a later point, I will *also* put up a build that works around this as described.

One important note: this replicates what we have on `main` right now, *not* what is on 1.1, but I do not *think* the few small changes should be relevant here. (If they are, we can easily make a version that matches more exactly.)

**Comment by effervescentia** [comment]
> Are you behind a VPN when you see this, or is it happening on “regular” network traffic?

Some of my team might use VPNs occasionally when travelling, but mostly we use "regular" network traffic (personally I'm using my home network)

> what other hardware and operating systems are you seeing this on?

I believe we've moved everyone off of the Intel MacBooks, so I think we can safely say everyone from my org is using M1/M2

> Here’s what I think is an actual minimal reproduction

I can confirm this results in the same symptoms as are triggered when downloading with `volta`

> you note that it’s taking all network bandwidth

Sorry I should be more technical, it causes network requests to never resolve
Once the request gets "stuck" then new requests that I make (loading a website, `curl`, `wget`) will not resolve until I quit the `vnr` process
I can still ping external sites such as `ping google.com` and the latency is not affected (other than a spike when I execute `vnr`)
From the outputs of `curl -v` and `wget` it appears that the request is sent, but it never reads the response

```
curl google.com -v
* Host google.com:80 was resolved.
* IPv6: 2607:f8b0:400b:803::200e
* IPv4: 142.251.33.174
*   Trying [2607:f8b0:400b:803::200e]:80...
* Connected to google.com (2607:f8b0:400b:803::200e) port 80
> GET / HTTP/1.1
> Host: google.com
> User-Agent: curl/8.6.0
> Accept: */*
>
```

```
wget google.com
--2024-07-25 15:21:22--  http://google.com/
Resolving google.com (google.com)... 2607:f8b0:400b:803::200e, 142.251.33.174
Connecting to google.com (google.com)|2607:f8b0:400b:803::200e|:80... connected.
HTTP request sent, awaiting response...
```

Finally here's the output of running `vnr`
https://gist.github.com/effervescentia/58bf6065537d4ad1a0e56fba1e96b322

From watching the network graph in Activity Monitor it appears like there is a single spike when `vnr` is executed, but it's not "using all the bandwidth" in the sense of monopolizing download bandwidth, rather somehow blocking responses from being processed

**Comment by chriskrycho** [comment]
@charlespierce one thing I notice in the gist with the full trace is that the sequence before things hang is:

- Volta (or the repro) invokes `attohttpc::get`
- `attohttpc` *successfully* connects to the endpoint (e.g. `nodejs.org:443`) and asks `rustls` for the TLS handshake
- `rustls`:
    - finds no cached session and is not resuming a session (although it successfully connected above)
    - sends its `ClientHello` side of the handshake
    - …hang

Since we suspect the issue is related to the second open request while the first is still open: What might be going wrong when starting a second handshake like this?

**Comment by effervescentia** [comment]
@chriskrycho hope you don't mind me trying to hold you to this

> I am actually inclined to ship a timeout but also warn! or possibly info! on the console in the case that it happens. I will open a PR doing just that tomorrow.

I'd much prefer a short-term solution being released in `volta` itself rather than spend 2 weeks chasing down all my coworkers to get a forked version installed only to have to repeat it in reverse once you've got a fix out 😅

**Comment by chriskrycho** [comment]
Ha! Totally fair to hold me to it, but even with pushing up a PR it’s likely going to be a “just install this” unless we (a) put it in 2.0 and (b) actually manage to release that very soon. I will try to put it up tomorrow or Wednesday though (despite notionally being on vacation).

**Comment by charlespierce** [comment]
I don't see anything obvious that would make the second request hang on the TLS Handshake step; though I'm about the farthest from an expert in TLS as you can get 😅 

For paths forward, a timeout is probably the easiest from a code change standpoint. Followed by removing the extra request and relying on the compressed size.

Another option would be to up it to 3 requests, but done in serial instead of two overlapping requests: First a `HEAD` request to get the `Content-Length` header / compressed size, then a `GET` with the `Range` header to get the isize value of the uncompressed size, and then finally a normal `GET` request to get the actual stream of data. This would hopefully avoid any issues with whatever is going on for overlapping requests, though it would add a little bit of overhead.

**Comment by charlespierce** [comment]
Just put up a PR #1812 that takes the 2nd of the 3 approaches: Removing the extra call entirely and relying on the compressed size for the progress bar. From my local (Windows-based) testing, I didn't notice any issues with the progress bar, but I'd be interested to know if there's anything noticeable on Unix.

**Comment by chriskrycho** [comment]
I’ll pull it and test it now!

**Comment by chriskrycho** [comment]
I merged that PR, so this should in principle be resolved on `main` at this point. We are going to *try* to get our 2.0 release out this week or next (not guaranteed, though!).

**Comment by effervescentia** [comment]
Thank you everyone who contributed to this change ❤️ can't wait to see this in the wild
