### ISSUE TITLE
how to use it in Jenkins or gitlab ci?

### ISSUE THREAD

**Issue by vaynevayne** [volta-cli/volta#1768]
Jenkins does not have PNPM or Volta. I need to install Volta first. Do I need to contact the operations personnel to install Volta? Or is there any way for the front-end to solve it?

**Comment by chriskrycho** [comment]
You will need to work with whoever on your team is responsible for managing the tools available on your CI setup to install it, much as you would for other dependencies. You will also need to make sure that your CI setup can talk to the internet to fetch the relevant versions *or* use the [Hooks](https://docs.volta.sh/advanced/hooks) configuration tool to point it to an internal repository.

Going to close this since it’s not an issue Volta needs to fix (though having some docs on CI configuration would be a great win for us at some point) so much as a question that needed answering. Thanks!
