### ISSUE TITLE
Suggestion to Introduce volta use as an Alias for volta pin

### ISSUE THREAD

**Issue by kortin99** [volta-cli/volta#1787]
I hope this message finds you well. I am writing to discuss a potential enhancement to the Volta tool that I believe could improve user experience, especially for those transitioning from other version management systems like nvm.

Currently, Volta utilizes volta pin as a command to pin a specific Node.js version. While functional, I've noticed that users coming from nvm might find it more intuitive if there were an alias that aligns more closely with their previous experience.

In `nvm`, and `nrm`, the use sub-command is typically employed to switch between different versions or npm registries. Would it be possible to consider introducing `volta use` as an alias for `volta pin`? This addition could facilitate a smoother transition for users and potentially enhance the overall usability of the tool.

```shell
volta use node@18         # as an alias for: volta pin node@18
```

This could facilitate a smoother transition for users coming from `nvm`. Similar to how `pnpm` supports both `install` and `add`, offering synonymous commands could enhance user experience.

**Comment by charlespierce** [comment]
Hi @kortin99, thanks for the suggestion! We've actually been talking a bit lately about issues with the verbs used in Volta command and how we can improve them to make things more intuitive and easier to understand. I have [an RFC](https://github.com/volta-cli/rfcs/pull/52) out right now about collapsing the core `install` and `pin` commands into a single command. I'm going to be updating that proposal sometime this week, but I'll also link this suggestion there because I think it fits into the same discussion.

Given that a change like this would very likely require an RFC anyway, I'd encourage you to follow / participate in that discussion.
