### ISSUE TITLE
can't install in Ubuntu 24

### ISSUE THREAD

**Issue by look4u-ovo** [volta-cli/volta#1813]
![图片](https://github.com/user-attachments/assets/8354116b-69f5-4db8-904a-f24f1783e33a)
Why can't I install it with commands? How to solve it , pls

**Comment by chriskrycho** [comment]
That looks like a problem with your network connection, rather than something specific to Volta, since it is curl reporting the issue. It is possible there is something with your network connection that is unhappy with the connection to `https://get.volta.sh`. You can open that directly in your browser and run it directly locally, though!

**Comment by look4u-ovo** [comment]
thanks
