### ISSUE TITLE
Interrupting download of a tool leaves the cache in a bad state

### ISSUE THREAD

**Issue by pzuraq** [volta-cli/volta#200]
I installed notion on a new computer yesterday and set it up to download Node v10, and it fell asleep midway through the install. The install failed, and when I went to try to rerun the command I kept getting errors.

I was able to reproduce this by sending a kill signal mid install (`CTRL + C`), and cleaning the cached binaries at `~/.notion` fixed the issue.

**Comment by pzuraq** [comment]
#134 would likely solve this issue as well

**Comment by charlespierce** [comment]
From discussion with @stefanpenner today, one good approach to fixing this would be to download the tools into the temp directory, and then atomically move it into the inventory directory once it has been downloaded and verified, so that if the download is interrupted we don't detect it as being available in the inventory.

**Comment by stefanpenner** [comment]
@charlespierce bonus, if available checksum once complete and before moving.
