### ISSUE TITLE
multiple checks for local distro?

### ISSUE THREAD

**Issue by dherman** [volta-cli/volta#210]
It looks like `NodeDistro::remote` and `NodeDistro::fetch` both check for a local distro for the requested version. This seems fishy -- is this checking for the same thing twice?

It seems like the check for a locally stored version should be abstracted out if possible. And `NodeDistro::fetch` is too long and should be broken up.

**Comment by charlespierce** [comment]
These two checks are conceptually different: In `NodeDistro::fetch`, we are checking if we need to do anything at all (if the requested version of Node is already available, we can no-op). In `NodeDistro::remote`, we are checking if we have the archive for the requested version of Node in the local cache or if we need to download it from the web.

That said, the current implementation of `inventory::serial` is checking the archive cache directory (`tools/inventory/node`) instead of the image directory (`tools/image/node`) to determine which versions count as "already available". So in practice, this check is duplicated, however I believe the bug is actually that the inventory should be checking the images themselves, instead of the cached archives, especially if we want to eventually support the `volta uninstall node` command #327

**Comment by chriskrycho** [comment]
I believe that is also directly relevant to the ways we'll need to survey things for the rest of the `volta list` implementation (#461).
