### ISSUE TITLE
get rid of notion-fail

### ISSUE THREAD

**Issue by dherman** [volta-cli/volta#334]
Since we now have a single `ErrorDetails` error type, I wonder if we can completely eliminate the `notion-fail` crate and all its abstractions. If I remember right, those were all needed to deal with the fact that there were _n_ Notion error types, but now there's only 1. It would be nice if `Fallible<T>` were just a shorthand for `Result<T, ErrorDetails>` or something like that.

This is off the top of my head so I could be wrong; needs some investigation.

**Comment by charlespierce** [comment]
On some further investigation into the usefulness of having separate crates for some operations (specifically the `layout` abstraction allowing us to version the layout separately from the overall project), we will likely have > 1 error types going forward, so instead of removing `volta-fail` completely, we should instead do #306 and remove the no-longer-supported `unknown()` method.
