### ISSUE TITLE
--verbose does not seem to work

### ISSUE THREAD

**Issue by thoov** [volta-cli/volta#362]
Running `notion --verbose install node 8` does not include any information.

I would assume that it would print out things like:

- The version that got resolved (ie 8 -> 8.11.2) 
- The url (and status code) of where notion is attempting to download from
- Where is notion placing node

**Comment by charlespierce** [comment]
`--verbose` Currently only affects error reporting, writing additional details in the case of an error. We've talked about including other reporting, but haven't implemented anything else so far. Thanks for the examples of info you'd like to see / would be useful when doing `--verbose`

**Comment by thoov** [comment]
@charlespierce When running `notion --verbose pin node 10` with an invalid `package.json` I get:

```
error: Could not parse project manifest
at /private/tmp/foobaz/package.json

Please ensure that the file is correctly formatted.

cause: expected `,` or `}` at line 53 column 5
Error details written to: notion-error-2019-04-17_10_34_56.719.log
```

It seems like the only thing that --verbose added was the "cause" line. That should be in the default error message and not behind the flag. To me conceptually `--verbose` should tell the user **what** notion is doing "behind the scenes" and not preventing users from actionable information.

cc: @dherman

**Comment by charlespierce** [comment]
That's true, that's what verbose errors does is show the underlying cause (and further, if there are nested causes). There are a couple of issues with showing all of the root causes by default:

* It makes the error messages longer and less concise. We explicitly wanted the errors to be concise to prevent the explosion of spam you see in e.g. `npm` when something goes wrong. We have the flag to allow that extra info to be shown, but by default want to keep things to-the-point.
* We don't have any control over the underlying error messages, they are generated by library dependencies, so their usefulness is questionable and not consistent. For example, one of the biggest complaints we got before the error message revamp was about how useless it was to see `not found (os error 2)`. That is one of the underlying error messages that we don't want to surface all the time, because it's just meaningless noise.

In the case of parsing errors specifically, I agree that providing some context of where the problem was makes sense, and we have an issue to track that: #280 Given that the parsing library we're using seems to give useful messages, it's likely that we can just include them.
