### ISSUE TITLE
Volta error: No Yarn version found in this project.

### ISSUE THREAD

**Issue by thoov** [volta-cli/volta#436]
Steps to reproduce:

1. `volta install yarn`
2. `volta pin node` (node is the only thing pinned)
3. `yarn -v`

Result:
```
Volta error: No Yarn version found in this project.

Use `volta pin yarn` to select a version (see `volta help pin` for more info).
```

**Comment by rwjblue** [comment]
@thoov - Is there a `yarn` version setup in the system in general? 

Specifically, I'm wondering if the error reported here is:

```
# fresh install

curl -sSLf https://get.volta.sh | bash
volta pin node
yarn -v
```

Or:

```
# fresh install
curl -sSLf https://get.volta.sh | bash

volta install yarn
volta pin node
yarn -v
```

**Comment by rwjblue** [comment]
Also, what was your expected output? Command not found?

**Comment by rwjblue** [comment]
I just did a quick test, looks like both of those snippets results in the same error. I was surprised that the second example failed, as I'd expected merging behavior similar to what we do with `hooks.json`.

At worst, we should have more specific prose in the error message, but I think we should probably "just work" (setting up a `yarn` that uses the pinned node if needed) in this case.

**Comment by thoov** [comment]
@rwjblue I updated the repro steps to include the extra `volta install yarn`

**Comment by charlespierce** [comment]
This might actually lead to a slightly different question: Should we treat the platform as a merge (in the way that we do with `hooks.json` currently) between the user defaults and the project-local settings? It's not immediately obvious to me either way.

One issue with doing so is that you could have a `yarn` default set up on your machine, and build your project assuming `yarn` is there, because it always works on your machine. But then when a different user who doesn't have `yarn` set up tries to run the project, it doesn't work. That's sort of the behavior we are trying to prevent, but at the same time we've moved away from being quite so overbearing with e.g. command passthroughs.

So I lean towards merging from a UX perspective, with the philosophy that Volta _enables_ you to do things in a cleaner way, but doesn't _require_ that you do so.

**Comment by rwjblue** [comment]
Yes, exactly. It might even be good to issue a warning that we've found `volta` in your `package.json` with a `node` version config, and that you are using `yarn` but it isn't configured in your project. I do agree that this type of mismatch is easy to get wrong but I think that having merging behavior (with or without a warning when we hit the fallback) is probably the right call.
