### ISSUE TITLE
Issue debugging ember executable 

### ISSUE THREAD

**Issue by thoov** [volta-cli/volta#460]
Command:

`node debug $(which ember) b`

Result:
```
(node:57868) [DEP0068] DeprecationWarning: `node debug` is deprecated. Please use `node inspect` instead.
< Debugger listening on ws://127.0.0.1:9229/fcf5ae6e-9dc5-46e6-bad8-20d019cc67ed
< For help, see: https://nodejs.org/en/docs/inspector
< Debugger attached.
< /Users/thoover/.volta/shim:1
< (function (exports, require, module, __filename, __dirname) { ����
<                                                               ^
< SyntaxError: Invalid or unexpected token
<     at new Script (vm.js:74:7)
<     at createScript (vm.js:246:10)
<     at Object.runInThisContext (vm.js:298:10)
<     at Module._compile (internal/modules/cjs/loader.js:657:28)
<     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
<     at Module.load (internal/modules/cjs/loader.js:599:32)
<     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
<     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
<     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
<     at startup (internal/bootstrap/node.js:236:19)
< Waiting for the debugger to disconnect...
debug>
```

At one point, stef mentioned, that there was discussion in resolving this by replacing which, with one that hid volta entirely. That would allow the above to "just work". Maybe there are other solutions?

Work around is to use: `node debug $(volta which ember) b`

**Comment by charlespierce** [comment]
We did discuss replacing `which`, but ultimately decided against trying to shim one of the core binaries that ships with the OS, given how commonly it is used and how bad it would be if we caused a failure of any kind. We also don't want to completely hide the existence of the shims in cases like this, because it would be extra confusing to run `which ember` and see the JS file, then run `ember` and get a `Volta error` for something that clearly doesn't come from the JS script.

As you noted, `volta which` is our replacement that lets you get at the relevant information in a way that is explicit about what it's doing, as opposed to trying to be completely invisible.

**Comment by rwjblue** [comment]
FWIW, I generally do `node --inspect-brk node_modules/.bin/ember b` instead of `node $(which ember) b`. I've had issues with the latter in a few scenarios (nvm + global yarn install + global npm install comes to mind).

**Comment by chriskrycho** [comment]
I do the same as @rwjblue for similar reasons. This might be another point in favor of a (well-designed) `volta run`.

**Comment by rwjblue** [comment]
Yes, agreed. `volta run` (with `--inspect-brk` / `debug` options) would probably work nicely here.

**Comment by stefanpenner** [comment]
I'm not super sure I agree with the rationale around `which` but It's sufficient small issue that I can accept your conclusions without much concern. Ultimately though the UX around failure here isn't great, could it be improved?

**Comment by lobsterkatie** [comment]
Just ran into this, and I'm not sure why this issue was closed - the error you get is still totally opaque. Is there any way to catch this and provide some better feedback to the user?
