### ISSUE TITLE
volta-install.sh script no-ops if you have current version installed

### ISSUE THREAD

**Issue by charlespierce** [volta-cli/volta#474]
If you run `./dev/unix/volta-install.sh --dev` or `./dev/unix/volta-install.sh --release` and already have the most recent version of Volta installed, the installer will no-op and just print out:

```bash
Version 0.5.4 already installed
```

The build still happens as expected, but the install step doesn't work unless you uninstall Volta before-hand.

**Comment by mikrostew** [comment]
Doh! This is because I combined the functionality of `boot-install.sh` and `install.sh` into a single script. This is the desired behavior if you are installing Volta from http://get.volta.sh (see #291). BUT not if you are using `--dev` or `--release` as a developer.

What I think _should_ happen is that those options should skip the check for version equality (but not any checks for the ability to upgrade from one version to another - those are still useful to run through).
