### ISSUE TITLE
Windows installer isn't uninstalling completely

### ISSUE THREAD

**Issue by dherman** [volta-cli/volta#5]
The Windows installer isn't properly deleting the Node installation directories on uninstall.

**Comment by charlespierce** [comment]
This is actually the expected behavior for Windows Installers / Uninstallers. The files that were created at run time in the User's `AppData` folder remain on the system, while the Installer removes the files that it installed, any registry entries, and undoes any changes to the Environment Variables.

It has the benefit of handling the case where a user uninstalls Notion and then reinstalls it, they will still have their local cache of versions available, so they won't have to re-download anything.
