### ISSUE TITLE
Support separate installation and "home" directories

### ISSUE THREAD

**Issue by frangio** [volta-cli/volta#506]
I'm packaging volta for Arch Linux, which essentially requires installing the main and shim executables in root-owned directories. In order to support installing tools without sudo, `VOLTA_HOME` would be set to a user-owned directory, and this means that `volta` and `shim` will not be in that directory.

This setup is only half-supported currently. The problem arises when installing a tool, say `typescript`. Volta will create a symlink `$VOLTA_HOME/bin/tsc -> $VOLTA_HOME/shim`, but this is a dangling symlink because the `shim` executable is elsewhere (e.g. `/usr/share/volta/shim`). I say half-supported because other than this issue, easily remedied by creating a symlink to the actual shim, everything seems to work great.

I'd like to ask what you think of this kind of setup in general. Is it important for volta to assume that `shim`, or `volta` itself, are in `VOLTA_HOME`? Would it be possible to change this assumption?

If the shim location were decoupled from `VOLTA_HOME`, I'm not sure what would be a good way of detecting or configuring where it actually is.

**Comment by charlespierce** [comment]
Hi @frangio, this is a great question! There's no technical reason why it wouldn't work, in fact the Windows install does just that: `shim.exe` and `volta.exe` are installed in the `Program Files` directory, while everything else is put into the user's Local App Data directory.

I think you hit on the core question: How do we identify the two directories (data and executables)? I have some ideas (env variables, config files), but we likely will need an RFC to work out all the potential edge cases.

Once we have a solution, we would likely also want to package the install into the various distro-specific installers. The benefit of the current installer is that it will work for users who don't have `sudo` access to their machines, since everything is installed in the home directory that they _can_ access. For administrator-managed installs, having an actual installer is likely better than a shell script that does everything.

**Comment by frangio** [comment]
> package the install into the various distro-specific installers

What do you mean by this exactly?

Something I have in mind too, which might be related, is that the installation script is doing too much.

For example, it creates the symlinks for node, npm and npx, and I feel that these should be created by volta itself once the user installs a node version. It would be consistent with installing any other tool, and will work slightly better in the scenario where volta is installed by the OS package manager.

Additionally, creating the directory structure in `VOLTA_HOME` seems unnecessary, since it is done by Volta when it runs anyway.

These are different issues but they have a common thread in that they relate to packaging volta itself.

**Comment by charlespierce** [comment]
By distro-specific installers I mean the package types that are used by each distro's package manager: `.rpm` on Red-Hat, `.deb` on Debian / Ubuntu, etc. For installers that require admin access, since they are installing in places other than the user's home directory, we probably want to have those available for as many distros as we can.

On the topic of how much the installer does, we actually need it to create the shim symlinks for `node` et al., because it's perfectly reasonable for the user to install Volta and then call `node` within a project, without ever having installed a default version.

Volta downloads tools on-demand, so if it encounters a version in a project's `package.json` that it hasn't found yet, it will download and make that version available automatically, without the user having to manually install it.

**Comment by frangio** [comment]
I think this issue was fixed by the new `volta setup` command, right?

**Comment by charlespierce** [comment]
@frangio Yes, I think it should be fixed with the `0.7.0` release including the `volta setup` command. Once we have that out of beta and have documentation around what is needed to create a custom / managed installer, then I believe we can close this.

**Comment by frangio** [comment]
I was able to create an Arch Linux AUR package. https://aur.archlinux.org/packages/volta
