### ISSUE TITLE
`volta pin` is inconsistent with `volta install` RE: multiple arguments

### ISSUE THREAD

**Issue by rwjblue** [volta-cli/volta#522]
`volta install` has been updated to accept multiple arguments (in the form `thing@version`), but `volta pin` does not support pinning more than one thing at a time.

Specifically `volta pin node@6 yarn@1.3.2` emits a warning saying that you must run `volta pin` twice:

```
❯ volta pin node@6 yarn@1.3.2
success: pinned node@6.17.1 (with npm@3.10.10) in package.json
error: Cannot pin Yarn because the Node version is not pinned in this project.

Use `volta pin node` to pin Node first, then pin a Yarn version.
```

**Comment by charlespierce** [comment]
I think what's happening here isn't that it can't accept multiple arguments, rather that it's pinning Node and then attempting to pin Yarn and failing because it thinks Node isn't pinned.

I believe the issue is that when we do the Node pin, we are writing the `package.json`, but we aren't updating our internal state, so when it gets to the Yarn pin, it still thinks there's nothing pinned.

**Comment by rwjblue** [comment]
Ya, that makes sense. Just to clarify, this is a use case we want to support right?

**Comment by charlespierce** [comment]
Yeah, absolutely, I believe it was just missed when we added support for multiple arguments to `pin`
