### ISSUE TITLE
How to install global packages(that don't have any executables) with volta ?

### ISSUE THREAD

**Issue by collegeimprovements** [volta-cli/volta#557]
Thanks for creating `volta`. It's fast and hygienic. 

I'm trying to install `pure-prompt` but volta doesn't allow it.  
What's the correct way to install such packages ?
 
```
➜  ~ yarn install -g pure-prompt
yarn install v1.19.0
error `--global` has been deprecated. Please run "yarn global add pure-prompt" instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
➜  ~ yarn global add  pure-prompt
Volta error: Global package installs are not supported.

Use `volta install pure-prompt` to add a package to your toolchain (see `volta help install` for more info).
➜  ~ volta install pure-prompt
error: Package has no executables to install.

Please verify the requested package name.
```

**Comment by charlespierce** [comment]
Hi @collegeimprovements, thanks for the kind words! For your question, please take a look at the discussion in #555, and add your use-case if it's different.

Looking at `pure-prompt`, it looks like it provides some shell scripts that get symlinked into the path for the shell, in order to set up the prompt? Given that, the easiest way to use this package with Volta would be to do:

```
$ VOLTA_UNSAFE_GLOBAL=1 yarn global add pure-prompt
```

Which will override the "Global package installs are not supported" message and allow you to run a global install. Since this package appears to be self-contained, and doesn't require interop with other global packages to work, it should be fine under those conditions (generally we disallow global installs since they don't work in an expected way with the multiple-node model that Volta uses).

**Comment by collegeimprovements** [comment]
Thanks a lot @charlespierce.  It works as expected :)
