### ISSUE TITLE
Volta - Questions 

### ISSUE THREAD

**Issue by collegeimprovements** [volta-cli/volta#569]
1. Is it possible to see which volta packages are outdated or updates are available ?  
This is very useful for global-packages and less useful for node.  
2. Is it possible to see which node-versions are available ? e.g. `n` shows it with `n ls` command.
3. Is it possible to  generate some file `like package.json  for node` with volta ? 
Then we can share that file across team and everyone can have same `node` and same global executables on their machine with single command e.g. `volta setup` or something like that?

**Comment by charlespierce** [comment]
Hi @collegeimprovements, thanks for the questions! I have some follow-ups to make sure I fully understand:

1. We don't currently have anything to check on the version, but this is a great idea! What you _can_ do is upgrade any given package using `volta install <package>@latest`, which will resolve the current latest version and upgrade you if you aren't on that latest. However, that doesn't solve the problem of knowing which packages need to be upgraded.

2. Can you expand on what you mean by which node versions are "available" and what the use-case is for looking that up? If you're looking for the versions that you have cached locally (in analogy with the `n ls` command), then `volta list` and it's related subcommands will show you that. It's worth noting, however, that the locally cached versions often aren't as important as in other Node version managers, since Volta will always look up and automatically download a version it encounters that isn't in the local cache already.

3. Is this for working within an existing JS package? I'm not sure I fully grasp the use-case here, and want to make sure I understand so I can answer accurately. I will say that we don't currently have a command for syncing the global executables, however.

**Comment by collegeimprovements** [comment]
Thanks a lot for reply @charlespierce.
1. Yes. I think for most cases `volta install <package>@latest` would be good enough. It would be great to know about the outdated packages at some point in future.
2. I mean what package-versions are available for install.
e.g. `n ls-remote` shows the following output.
```
λ › n ls-remote                                                                                                                 ~
Listing remote... Displaying 20 matches (use --all to see all).
12.12.0
12.11.1
12.11.0
12.10.0
12.9.1
12.9.0
12.8.1
12.8.0
12.7.0
12.6.0
12.5.0
12.4.0
12.3.1
12.3.0
12.2.0
12.1.0
12.0.0
11.15.0
11.14.0
11.13.0
```
And if we have node-12x.x installed and in future node-13 or node-14 is released then those can be seen with this command.

3. It's great to have thing. E.g. I'm using `mac` and if I have to setup another `mac`, I can generate a `Brewfile` -> copy it on to another mac and run `brew bundle`. It will install all required packages for mac. Similarly for global package it would be great to have similar kind of command. That command would just create some file like `Brewfile` for `package.json` which can be shared across computer and with one command like `bundle brew` or `yarn` all required packages are installed. 
In essence this command would be just some file-version of `volta list` command. 
e.g. I have the following packages installed. 
``` 
λ › volta list  --format=plain                                                                                                  ~
runtime node@12.12.0 (default)
package-manager yarn@1.19.1 (default)
package cypress@3.4.1 / cypress / node@12.12.0 npm@built-in (default)
package fkill-cli@5.2.0 / fkill / node@12.12.0 npm@built-in (default)
package gtop@1.0.1 / gtop / node@12.12.0 npm@built-in (default)
package iponmap@1.1.0 / iponmap / node@12.12.0 npm@built-in (default)
package pageres-cli@5.0.0 / pageres / node@12.12.0 npm@built-in (default)
package parcel@2.0.0-alpha.1.1 / parcel / node@12.12.0 npm@built-in (default)
```
It would be great to generate some file and put it in my `dotfiles` repo. This way it can be tracked in git and can be shared with others.

**Comment by charlespierce** [comment]
@collegeimprovements Those make sense, thanks for clarifying! To answer the original questions, we don't currently have anything like `n ls-remote` or `brew bundle`, but I can definitely see the use-case for both. These are all great suggestions, I'll create issues so each of them can be tracked independently.

Thanks for raising them!

**Comment by collegeimprovements** [comment]
Thanks a lot @charlespierce  😊

**Comment by charlespierce** [comment]
Closing in favor of #572, #573, #574 tracking each suggestion independently. Thanks again @collegeimprovements!
