### ISSUE TITLE
Adding suffix to version in `volta -v` to signify if you're using a dev build

### ISSUE THREAD

**Issue by fusion2004** [volta-cli/volta#576]
What do y'all think about making the version command add a suffix like `-dev` to the outputted version if you're running a development build of volta?

E.g.:
```
$ volta -v
0.6.3-dev
```

Or is there maybe some other easy way to figure this out that I missed?

**Comment by charlespierce** [comment]
@fusion2004 That's a great idea! There isn't currently an easy way to tell that you are using a dev build instead of the latest production build.

**Comment by mikaoelitiana** [comment]
would checking the existance of `.git` be a way to determine we are in dev build?

**Comment by charlespierce** [comment]
@mikaoelitiana I don't think that would work, because the production builds are also done in the same directory, so there will always be a `.git` folder around. However, it looks like Rust has a conditional compilation flag you can use to detect a debug build (as opposed to a `--release` build):
```rust
#[cfg(debug_assertions)]
```
So we should be able to use that to conditionally add the `-dev` suffix to the output in [`src/cli.rs`](https://github.com/volta-cli/volta/blob/master/src/cli.rs#L51)

**Comment by charlespierce** [comment]
Closed via #607
