### ISSUE TITLE
`gulp-cli` does not appear to work

### ISSUE THREAD

**Issue by dustinsoftware** [volta-cli/volta#586]
When trying to run `gulp` from the command line, it crashes immediately

```
PS > volta install gulp-cli
success: installed gulp-cli@2.2.0 with executables: gulp

PS > gulp -v
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '\\?\C:\Users\dustin.masters\AppData\Local\Volta\tools\image\packages\gulp-cli\2.2.0/lib/versioned/'
    at Object.readdirSync (fs.js:870:3)
    at Object.<anonymous> (\\?\C:\Users\dustin.masters\AppData\Local\Volta\tools\image\packages\gulp-cli\2.2.0\index.js:31:17)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (\\?\C:\Users\dustin.masters\AppData\Local\Volta\tools\image\packages\gulp-cli\2.2.0\bin\gulp.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:971:30) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '\\\\?\\C:\\Users\\dustin.masters\\AppData\\Local\\Volta\\tools\\image\\packages\\gulp-cli\\2.2.0/lib/versioned/'
}
```

Environment: Windows 10 1903 x64
Volta version: 0.6.4

**Comment by pjking07** [comment]
I'm not familiar with the internals of `volta` yet, but with some poking I found:

1. gulp-cli attempts `readdirSync` with a concatenated path (rather than, e.g., `join()`)
https://github.com/gulpjs/gulp-cli/blob/master/index.js#L30-L31
2. when running via volta, the gulp-cls `__dirname` starts with `\\?\C:\` per the error message
3. `readdirSync` throws the error:
  a. `readdirSync` supports `\\?\C:\` (DOS?) paths
  b. `readdirSync` supports mismatched path separators
  c. `readdirSync` doe **not** support both `a` and `b` at the same time

![image](https://user-images.githubusercontent.com/1873305/67803699-97f69b80-fa5b-11e9-8c70-05b1473a5b25.png)

Hope that helps!

**Comment by chriskrycho** [comment]
That _looks_ like there's an upstream issue, in that Gulp is misbehaving in its path handling, but this seems to be breaking in a way in Volta it's *not* with e.g. the base Node installer and/or nvm-windows?

**Comment by pjking07** [comment]
Yes, that's correct. We were also curious whether volta did anything explicit to `__dirname` and `__filename`.

**Comment by chriskrycho** [comment]
The problem seems to be the specific combination of the way we canonicalize the path (using Rust's `Path::canonicalize`) when we invoke Gulp with Gulp's incorrect handling of the path itself. However, I *think* this is mostly an upstream in that we're actually doing the *right* thing and Gulp just needs the fix. Does that seem correct to you, @charlespierce?

**Comment by charlespierce** [comment]
@chriskrycho Yep, that sounds accurate. We're using a valid extended path (which means we handle the case when the path is longer than 260 characters), and Gulp is mishandling that case.

**Comment by charlespierce** [comment]
Created https://github.com/gulpjs/gulp-cli/pull/201 to resolve the upstream issue, but it doesn't look like that project has changed much recently. For usability, we should investigate whether it's possible to avoid using extended-length paths.
