### ISSUE TITLE
Windows: system error if VCRUNTIME140.dll is not previously installed

### ISSUE THREAD

**Issue by pjking07** [volta-cli/volta#587]
# Steps to reproduce

1. Start a new instance of Windows Sandbox, execute the following in the Sandbox.
2. Install volta 0.6.4 via the [msi](https://github.com/volta-cli/volta/releases/download/v0.6.4/volta-0.6.4-windows-x86_64.msi)
3. Open Command Prompt, execute `volta -v`

# Expected Result

volta writes `0.6.4`

# Actual Result

We get a System Error from volta.exe:

`The code execution cannot proceed because VCRUNTIME140.dll was not found. Reinstalling the program may fix this problem.`

_Note: `volta -v` in Powershell fails silently_

# Impact

Volta won't run in this configuration.

# Workaround

Download and install [Microsoft Visual C++ 2015 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=52685), then try again.

**Comment by chriskrycho** [comment]
Thanks for the report! @charlespierce thoughts on the mechanics for tackling this? Should it just be more docs and making sure that PS does the right thing so it doesn't fail silently here?

**Comment by pjking07** [comment]
I have not modified installers in a _long_ time, but I would expect the redistributable to be included in (or downloaded by) the installer. Cf. [WIX How To: Install the Visual C++ Redistributable with your installer](https://wixtoolset.org/documentation/manual/v3/howtos/redistributables_and_install_checks/install_vcredist.html). 

Notably, Microsoft notes some cautions when considering merge modules. Cf. [Redistributing Components By Using Merge Modules](https://docs.microsoft.com/en-us/cpp/windows/redistributing-components-by-using-merge-modules?view=vs-2019).

**Comment by charlespierce** [comment]
Not sure about the PowerShell silently failing part, I don't know that there's much we can do about that, however my thought was exactly what @pjking07 just linked: Including the dependency in the installer itself. Thanks for linking those! I'll read through because I'm far from an expert in installers either 👍

**Comment by charlespierce** [comment]
@pjking07 I don't currently have a development machine with Windows 10 Pro to use the Windows Sandbox, so would you be willing to test the changes with the following installer (which includes the Visual C++ runtime Merge Module)?

[volta-0.6.5-x86_64.msi.zip](https://github.com/volta-cli/volta/files/3812320/volta-0.6.5-x86_64.msi.zip)

If that works, then I'll create a PR so all future installers will have the merge module included. Thanks!

**Comment by pjking07** [comment]
That worked perfectly on Windows Sandbox :shipit:

**Comment by pjking07** [comment]
And the upgrade path on my host Windows worked fine as well

**Comment by khirakawa** [comment]
Hi @charlespierce! We're running into this issue in the latest v2.0.0 release.  The issue was reproduced on a Windows 11 Pro (build 22631.4037) in a Parallels VM (ARM).  Volta was installed using `winget install Volta.Volta`

![Screenshot 2024-08-14 at 6 47 01 AM](https://github.com/user-attachments/assets/37bcfb39-17ce-4fa2-9cb3-c6e3094d194e)

Downgrading to v1.1.1 resolves the issue.
