### ISSUE TITLE
Installing `pre-release` with `volta-install.sh`

### ISSUE THREAD

**Issue by s0kil** [volta-cli/volta#621]
Does the install script also support updating to a `pre-release` version?

**Comment by charlespierce** [comment]
Hi @s0kil, by `pre-release` do you mean the recent `0.7.0-betaX` releases, since all of the Volta releases so far are marked as "Pre-Release" since we haven't yet hit 1.0 functionality?

If so, then the script doesn't fully support that, because part of the new behavior is updating the scripts themselves. That said, if you are interested in trying that out, you can download the new installer at: https://github.com/volta-cli/volta/blob/e0290c2d7b0e80bf64e7c5d403789bc51678d16c/dev/unix/volta-install-updates.sh and then execute that script with the `--version 0.7.0-beta2` flag and it should work correctly.

Also, we should be releasing it as an official release (not a `-beta` release) soon, if you'd prefer to wait until the official installer supports the new version.

**Comment by s0kil** [comment]
@charlespierce I missed the `--version` flag, this works now:

`curl https://raw.githubusercontent.com/volta-cli/volta/master/dev/unix/volta-install-updates.sh | bash -s -- --version 0.7.0-beta2`
