### ISSUE TITLE
Infinite loop when running `npm i`

### ISSUE THREAD

**Issue by dustinsoftware** [volta-cli/volta#630]
After installing `v0.7.0-beta3`, I've now observed a few cases where running `npm i` causes thousands of processes to spawn. It's hard to tell if this is new behavior; I will attempt a downgrade if I can find a repro. Whenever this happens I have to log out of my workstation to get all the processes to close.

(unreliable) Steps to repro:
- Open a new instance of Powershell
- Run `npm i`, observe it works
- Run `npm i` again, observe it hangs and thousands of processes spawn

![Screen Shot 2019-12-26 at 12 01 46](https://user-images.githubusercontent.com/942358/71483897-e1533500-27d7-11ea-8f56-ab436697a648.png)
![Screen Shot 2019-12-26 at 12 01 37](https://user-images.githubusercontent.com/942358/71483898-e1ebcb80-27d7-11ea-9327-7274e34866e9.png)
![Screen Shot 2019-12-26 at 12 01 29](https://user-images.githubusercontent.com/942358/71483900-e1ebcb80-27d7-11ea-9fd1-304406bf44e2.png)
![Screen Shot 2019-12-26 at 11 20 01](https://user-images.githubusercontent.com/942358/71483901-e1ebcb80-27d7-11ea-946e-ccdd6e806a81.png)

**Comment by chriskrycho** [comment]
Yikes! 😱 Thank you for reporting this (and for testing the beta for us)! A couple follow-up questions—

- does this ever show up with `yarn` or only with `npm`?
- does it show up more in specific repos?
- does it happen in non-Powershell environments on Windows, e.g. in CMD?

**Comment by charlespierce** [comment]
@dustinsoftware That's not good behavior 😦 I know I ran into issues with this in the past, and I documented some of what I found in this issue: https://github.com/volta-cli/volta/issues/577 However, since we're using the `cmd.exe /C` "workaround", it's a bit surprising to see it crop up again!

Out of curiosity, is this in a project that has `node` pinned, or is it using the default Node / npm version (e.g. outside of a project or in a non-pinned project)? If it's outside of a pinned project, do you have `npm` available from a separate installation, or is Volta the only Node / npm installation you have?

Thanks for reporting and helping us test!
