### ISSUE TITLE
Can't install windows-build-tools

### ISSUE THREAD

**Issue by DanielRosenwasser** [volta-cli/volta#681]
Volta has generally been working well for me, but I recently tried using it to build on the VS Code repo. 

The Visual Studio Code repo apparently has some fancy stuff going on that expects Windows users to either have VS2017 installed, or [windows-build-tools](https://www.npmjs.com/package/windows-build-tools); however I think that because this package just exists to install a bunch of Windows executables globally, Volta isn't happy with it.

```
> volta install --verbose windows-build-tools
[verbose] No custom hooks found
[verbose] Found project manifest in 'C:\Users\Daniel\vscode'
[verbose] Found default configuration at 'C:\Users\Daniel\AppData\Local\Volta\tools\user\platform.json'
[verbose] Using npm@6.13.4 from default configuration
[verbose] Running command: `"cmd.exe" "/C" "npm" "view" "--json" "windows-build-tools@latest"`
[verbose] [parsed package metadata (single)]
NpmViewData { name: "windows-build-tools", version: Version { major: 5, minor: 2, patch: 2, pre: [], build: [] }, dist: RawDistInfo { shasum: "1aabd53e40fb0a34cbd4b1023220573fab4dc772", tarball: "https://registry.npmjs.org/windows-build-tools/-/windows-build-tools-5.2.2.tgz" }, dist_tags: {"alpha": Version { major: 4, minor: 0, patch: 0, pre: [AlphaNumeric("alpha"), Numeric(13)], build: [] }, 
"latest": Version { major: 5, minor: 2, patch: 2, pre: [], build: [] }, "beta": Version { major: 3, minor: 0, patch: 0, pre: [AlphaNumeric("beta"), Numeric(3)], build: [] }} }
[verbose] Found windows-build-tools latest version (5.2.2) from https://registry.npmjs.org/windows-build-tools/-/windows-build-tools-5.2.2.tgz
[verbose] windows-build-tools@5.2.2 has already been fetched, skipping download
error: Package has no executables to install.
```

I'm not familiar enough with all of this, but I guess my questions are:

* Is WBT fundamentally incompatible with Volta?
* If it's compatible, does WBT just have to specify global executables that it will place in the system?
* Or if it's none of these, is there something Volta can do?

**Comment by charlespierce** [comment]
Thanks for the questions @DanielRosenwasser! It looks like the WBT npm package exists as a shortcut script for fetching and running a collection of native installers, it doesn't provide any executables directly itself. This isn't exactly _incompatible_ with Volta, but it's _separate_ in that the tools installed by WBT are managed by the OS install process, not by Node. So Volta can't reasonably provide its context-aware shims for those tools.

That's where the error is coming from, the WBT `package.json` doesn't declare any binaries in the Node / npm way (as members of a `bin` object), so Volta prevents installing it because it doesn't do anything that Volta can support. There are a few packages that behave similarly, so it's possible that Volta should support installing any package, perhaps with just a warning if the package doesn't provide any binaries that Volta can manage.

All that said, looking at the WBT package itself, it looks like the script will always run after the package is installed, even on local installs, so there really isn't a technical reason why you would need to install it globally. You could create a dummy npm package and run `npm install windows-build-tools` and it should provide the same behavior as globally installing it.

In fact, since it doesn't appear to have any uninstall scripts / behavior, you should be able to achieve the same install behavior using `npx windows-build-tools` (Though in that case it looks like `npx` eats all of the output from the command, so if something goes wrong it's difficult to debug).

Does that answer the questions?

**Comment by dieeisenefaust** [comment]
@charlespierce, I just ran into this issue as well immediately after deciding to give Volta a try. Your npx approach didn't work for me - it threw an error - but creating a dummy package.json and then running a local install worked. 

However, I agree that this is a cumbersome workaround and while i don't have any specific examples, I worry that there may be edge cases where this approach wouldn't work. I would definitely vote on allowing Volta to install any package and providing a warning as you suggested.

**Comment by charlespierce** [comment]
With Volta 0.9.0, this should now work out-of-the-box. We no longer require that packages have an executable, and the install process goes through the normal package manager installer.
