### ISSUE TITLE
Install script failure: installer tried to extract archive with bad name

### ISSUE THREAD

**Issue by rhcarvalho** [volta-cli/volta#686]
Trying to install `volta` today, I run into this:

```console
$ curl https://get.volta.sh | bash -s -- --skip-setup
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11925    0 11925    0     0  15406      0 --:--:-- --:--:-- --:--:-- 15406
  Installing latest version of Volta (0.7.2)
    Checking for existing Volta installation
    Fetching archive for macOS, version 0.7.2
######################################################################## 100.0%#=#=-#  #  ######################################################################## 100.0%
    Creating directory layout
  Extracting Volta binaries and launchers
tar: Error opening archive: Failed to open '
/var/folders/5f/7dv67jv51d55gzm_723cp1d80000gn/T/tmp.lXjtBvvw/volta-0.7.2-macos.tar.gz'
```

```console
$  file /var/folders/5f/7dv67jv51d55gzm_723cp1d80000gn/T/tmp.lXjtBvvw/volta-0.7.2-macos.tar.gz
/var/folders/5f/7dv67jv51d55gzm_723cp1d80000gn/T/tmp.lXjtBvvw/volta-0.7.2-macos.tar.gz: gzip compressed data, last modified: Thu Feb 13 01:20:12 2020, from Unix, original size modulo 2^32 16739840
```

Taking a closer look, notice that the archive exists but the installer script tried to decompress `\n/var/.../volta...tar.gz`, the newline character should not be there.

---

For what it's worth, I downloaded and patched the installer and installed successfully, PR will follow.

**Comment by charlespierce** [comment]
Hi @rhcarvalho, thanks for reporting this! It's very strange for a couple of reasons: First, I don't see how a newline could have shown up in that path in the first place, unless `mktemp -d` output a newline character at the start of the `PATH`. Second, it seems like `curl` handled it fine as an output directory, unless it does some internal sanitization to trim the inputs.

Does running `mktemp -d` directly in your terminal output extra newlines? I'm curious if we can figure out what the root cause of the bad filename is, which would result in a more robust fix for the installer, preventing this from cropping up again somewhere else.

**Comment by rhcarvalho** [comment]
I see where it comes from:

```
 17 download_release_from_repo() {
 18   local version="$1"
 19   local os_info="$2"
 20   local tmpdir="$3"
 21
 22   local filename="volta-$version-$os_info.tar.gz"
 23   local download_file="$tmpdir/$filename"
 24   local archive_url="$(release_url)/download/v$version/$filename"
 25
 26   curl --progress-bar --show-error --location --fail "$archive_url" --output "$download_file" && echo "$download_file"
 27 }
```

`download_release_from_repo` prints not only the `echo "$download_file"` but whatever `curl` may output. (And it may depending on `curlrc`.)

I've updated #687 for a more robust patch.

**Comment by charlespierce** [comment]
Ah ha, that makes sense. Great catch!
