### ISSUE TITLE
Caching Binaries in CI

### ISSUE THREAD

**Issue by alexlafroscia** [volta-cli/volta#705]
We're using Volta to manage out Node and Yarn versions both locally as well as in CI. The ability to use one tool across both environments is great!

We're running into an issue this morning where our Node downloads keep failing for one reason or another, which has sent our CI builds into disarray. It seems we would really benefit from the ability to cache the downloaded binaries between CI runs to avoid these kind of issues (and the need to download them on _every_ job run).

My question is: what's the appropriate way to either control or print the directory in which Volta stores the binaries it has downloaded? I would like to use that in conjunction with my CI provider's caching functionality to restore the Node binaries before Volta attempts to download them again.

**Comment by alexlafroscia** [comment]
Would we want to cache the entire `$HOME/.volta` directory? Or only part of it?

**Comment by charlespierce** [comment]
@alexlafroscia Good question! I think the most straightforward solution would be to cache the entire `$HOME/.volta` directory. That's a little more than would be strictly necessary to cache the binaries, but it ensures that you don't have to deal with the internals of how Volta manages state (which is subject to change between versions). It's also not _that_ much more than the binaries, since the binaries are a large majority of the space taken up by that directory. The rest is mostly text files that are very small and shouldn't have an impact on the cache time.

**Comment by alexlafroscia** [comment]
Cool! I'll try that once nodejs.org seems to be stable again and open a new issue if it doesn't seem to work right.
