### ISSUE TITLE
Default to use "engines" value as pinned or have configuration to use "engines" value

### ISSUE THREAD

**Issue by chrisirhc** [volta-cli/volta#742]
Hi there, maybe I'm missing something obvious but for pinning Volta in a project, why doesn't Volta simply use the values from the `engines` by default?

We have projects with package.json files contain:

```json
  "engines": {
    "node": "10.16.0",
    "npm": "6.9.0",
    "yarn": "1.16.0"
  },
  "volta": {
    "node": "10.16.0",
    "yarn": "1.16.0"
  },
```

Could we leave out the "volta" config when the "engines" field exist or do something like:

```json
  "engines": {
    "node": "10.16.0",
    "npm": "6.9.0",
    "yarn": "1.16.0"
  },
  "volta": {
    "useEngines": true
  },
```

And in this scenario it'd ignore the `npm` value safely?

**Comment by charlespierce** [comment]
Hi @chrisirhc, there are actually a couple of reasons we avoid using `engines`, one technical and one conceptual.

First, from a technical standpoint, the `engines` key supports semver ranges (like `8.* || 10.* || >= 12`), while the `volta` entries need to be a specific version. We do this for performance and so that the environment is repeatable. We have the ability to resolve a version requirement, but doing so would require that we re-evaluate the setting in `engines` on every execution (which could require a network call) and it would mean that a new version being published would change the active version of Node right out from underneath you. We chose instead to make the version itself pinned so that changing it requires an active step on the part of the team.

Next, conceptually, the two fields represent something _slightly_ different: `engines` is used to indicate on which versions your package can _run_, while `volta` is used to specify the versions used to _develop_ your package. Though there's natural overlap, the two are distinct.

For those reasons, we ultimately decided against trying to re-use the `engines` key. This does lead to a bit of duplication, as you noted, but we felt it was best way forward at the time.

**Comment by charlespierce** [comment]
Closing as it's been a few weeks. Feel free to re-open if you have other questions!

**Comment by t-ricci-delta** [comment]
In my opinion this phrase would be false:

> but doing so would require that we re-evaluate the setting in engines on every execution (which could require a network call) and it would mean that a new version being published would change the active version of Node right out from underneath you

It should use the latest version that you have locally that is within the specified range. So it will maybe require a network call just the first time you get into the directory (first time installing a node version that is present in the package.json)

You may take a look as there is another package accomplishing something along those lies: https://github.com/wbyoung/avn

@charlespierce

**Comment by charlespierce** [comment]
@t-ricci-delta That's definitely one way to work around the issue, however a solution relying on the local cache has a few related issues:

1. Volta will automatically download a new version when it detects that's necessary, which could cause a situation where switching directories and running a node command could change the active version on a completely unrelated project. For example:
    * Project A has `engines: "14.* || 16.*"`, Project B has `volta: { node: "16.13.0" }`
    * You currently only have one version in your local cache: `14.18.2`
    * If you run `node -v` in Project A and Volta relies on the local cache, you would see `14.18.2`
    * If you then switch to Project B and run `node -v`, Volta will automatically download `16.13.0` and use that.
    * If you then switch _back_ to Project A and run `node -v`, Volta will now have `16.13.0` so it will show that (even though on the surface nothing changed with Project A).
2. Unlike many similar tools, Volta doesn't maintain an "active" state at all, it evaluates the context on each execution. This allows it to be fully responsive to any changes and avoid slow shell startup / directory changes, but comes with requirements around the startup latency. While removing the potential need for a network call helps, even using the local cache will require that we catalogue all of the available versions of tools on each execution, in order to compare them with the `engines` requirements. That exhaustive search I/O can be relatively expensive. With a single precise version, we can check the cache with a single filesystem check, with a range we need to do a lot more. 

Lastly, it's important to note that while the technical limitations are a part of why we chose not to use `engines`, they aren't the main reason. The bigger factors were the conceptual difference of `engines` and Volta's version (as described in the previous comment) and Volta's commitment to a consistent, repeatable environment. With a range of versions, there's no way to guarantee that the version you used yesterday is exactly the same as the version you use today.

**Comment by jakobrosenberg** [comment]
@charlespierce If switching between versions is an issue, the `engines` field should be pinned to a single version. It sounds like Volta is trying to hide a bad configuration rather than expose it. Something you'd prefer to happen in dev, not production.

If I clone a repo with `engines: "14.* || 16.*"`, I might not know what matching version Volta will use, but the author has already specified which versions work, so it's not an issue. The alternative is that Volta uses eg. v19, the project breaks and I then have to debug the issue.

**Comment by charlespierce** [comment]
@jakobrosenberg It's less about hiding bad configuration and more Volta's commitment to consistent, repeatable environments. There's also the conceptual difference between dev / build-time requirements and consumer guarantees. For example, a library could be written where the published code itself works on Node 14 or 16, but the build toolchain requires features from Node 16, so it _has_ to be built using that version, even if it can be consumed from either.

That said, there's definitely room to leverage the information from `engines` to add extra value and improve the development experience. I believe we already have an issue tracked to consider `engines` when finding an appropriate version using `volta pin`. And separately, since we have the data, I could see showing a warning or other message letting a user know that the version of Node that Volta resolves (e.g. the global default) doesn't align with the `engines` requirements, so there may be a mismatch. Actually switching versions opaquely based on an arbitrary range, however, we feel falls outside of the expectations of users and the goals of Volta to be both consistent and transparent.

**Comment by ProLoser** [comment]
Would love a `volta pin engines` command or something that uses the engines key to generate pinned values

**Comment by nwidynski** [comment]
@charlespierce Would something speak against loading from `engines` only when the value is pinned to a specific version?

```jsonc
// Would work
{ "engines": { "node": "22.0.0" } } 
```
```jsonc
// Would NOT work
{ "engines": { "node": "22.x.x" } } 
```

**Comment by ProLoser** [comment]
It would add extra confusion when it doesn't work

**Comment by ljharb** [comment]
Now that devEngines exists, that’s what should be used, not engines.
