### ISSUE TITLE
Install yarn 2

### ISSUE THREAD

**Issue by SBoudrias** [volta-cli/volta#807]
It looks like yarn 2 releases are done in a different way. Is there anyway to use it with Volta?

```sh
$ yarn --version
Volta error: Could not download yarn@2.2.0
from https://github.com/yarnpkg/yarn/releases/download/v2.2.0/yarn-v2.2.0.tar.gz

Please verify your internet connection and ensure the correct version is specified.
Error details written to /Users/SBoudrias/.volta/log/volta-error-2020-09-02_17_48_35.543.log
```

```sh
$ volta install yarn@2.2.0
error: Could not download yarn@2.2.0
from https://github.com/yarnpkg/yarn/releases/download/v2.2.0/yarn-v2.2.0.tar.gz

Please verify your internet connection and ensure the correct version is specified
```

**Comment by charlespierce** [comment]
Hi @SBoudrias, thanks for asking! We actually just updated Volta to fetch Yarn from `registry.npmjs.org` instead of the GitHub releases in the most recent release, Version 0.8.7. So that should solve that particular problem.

However, there is still an outstanding issue that may make Volta misbehave with Yarn 2.0: We currently don't support Yarn Plug'n'Play behavior, which is enabled by default in Yarn 2.0. So what you may see is that global binaries that are trying to delegate to the local version will fail, because we are looking for them in `node_modules/.bin`, which doesn't exist under Yarn 2.0 / PnP.

See https://github.com/volta-cli/volta/issues/651 and https://github.com/volta-cli/volta/issues/158 for more info on our previous investigations into Yarn 2.0 and PnP
