### ISSUE TITLE
volta pin command should also update package.engines.yarn if present

### ISSUE THREAD

**Issue by micahstubbs** [volta-cli/volta#841]
volta pin command should also update package.engines.yarn if present

reasoning: as a user of volta, when I run the command `volta pin yarn@latest` in my project, I have to manually update the `package.engines.yarn` field as well. 

It would be more ergonomic if volta would just update this field as well for me, or at least present some cli dialog prompt asking me if I want to `package.engines.yarn` as well.

**Comment by micahstubbs** [comment]
another option would be to detect that the `package.engines.yarn` field is set when a user runs `volta setup` and explain to the user that using `package.engines.yarn` and `volta` together is not recommended.

**Comment by micahstubbs** [comment]
either way, whether the the volta tool helps me upgrade all my config in sync or whether it tells me not to use potentially conflicting config, I feel like volta should be smart enough to anticipate this inconsistent config state (two different versions of `yarn` specified in my `package.json` and help me the user avoid it 😄

**Comment by charlespierce** [comment]
We actually discussed this a fair amount early on in the project and ultimately decided against re-using or interacting with `engines` at all. The reason for that is that they represent two conceptually different (though similar) things:

- `engines` represents the _range_ of versions that your package works under. It's used by _consumers_ of your package to determine if their environment is consistent or not (e.g. `npm` will throw an error if you attempt to install a package using a Node version that is incompatible with the package's `engines` key).
- `volta` represents the _specific_ versions that are used in developing and building your package. It's used by _developers_ of your package to ensure that everyone has the same environment when working on the package.

`engines` should be set to the widest possible range that your library supports, to ensure compatibility with the highest number of consumers, while `volta` must be set to specific versions (no wildcards / ranges), to ensure that the environment is repeatable. Given that, I'm not sure if there's a way for Volta to meaningfully interact with `engines`, since there's no way for us to know the full spread of possible versions that your library supports (or doesn't support).

For some more discussion of `engines`, see #742 and #355
