### ISSUE TITLE
Show warning for Node Windows versions prior to v6.2.1

### ISSUE THREAD

**Issue by idleberg** [volta-cli/volta#847]
It appears that [Node v6.2.1](https://nodejs.org/dist/v6.2.1/) is the first version that provides zipped versions of the Windows build. Hence versions prior to that will fail to install.

**Example**

```sh
$ volta install node@5.4.1
error: Could not download node@5.4.1
from https://nodejs.org/dist/v5.4.1/node-v5.4.1-win-x64.zip

Please verify your internet connection and ensure the correct version is specified.
```

While I would understand that you might not want to support such old versions of Node, I think Volta could handle this exception more gracefully and display a better error message.

Potential workaround: allow users to provide a custom URL flag, maybe with a "danger zone" confirmation.

**Comment by charlespierce** [comment]
Hi @idleberg, thanks for raising this! Looking through the releases, it appears that it's not quite as simple as versions < 6.2.1 not having Windows zip file releases, as the later LTS 4.* versions _do_ have the zip files. That said, we definitely should handle this case more gracefully and notify the user that there isn't a release package available, possibly with a CTA to try a newer version.

We have a (long-standing) issue to actually confirm OS / architecture availability when finding a Node version #34, and I think this would fall under that because we could detect that the windows zip isn't available and show an error message that is more clear.

**Comment by charlespierce** [comment]
Added a comment on that issue, please follow that one for updates!
