### ISSUE TITLE
npm not installed in a way IntelliJ can see

### ISSUE THREAD

**Issue by davidgilbertson** [volta-cli/volta#852]
I'm running a fresh install of Windows 10 and I use IntelliJ.
I installed Volta, and ran `volta install node` and checked that it also installed `npm`. Both are working fine. (I'm a fan so far!)

But in IntelliJ, in the settings, it can't find `npm`.

![image](https://user-images.githubusercontent.com/4443482/95919162-d74b0300-0df8-11eb-8029-7ee1eb484c69.png)

I next tried explicitly doing `volta install npm` but that didn't help. I also tried putting `C:\Program Files\Volta\npm.exe`, `C:\Program Files\Volta\npm.cmd`, and `C:\Program Files\Volta` in the package manager field, none of which worked.

The JetBrains page on these settings: https://www.jetbrains.com/help/idea/2020.2/installing-and-removing-external-software-using-node-package-manager.html?utm_source=product&utm_medium=link&utm_campaign=IU&utm_content=2020.2#ws_npm_yarn_configure_package_manager

**Comment by charlespierce** [comment]
Hi @davidgilbertson, this is tracked in #729. It appears the core issue is that IntelliJ is looking for the directory of the `npm` _package_, not a path to the binary itself. That directory is currently found in `%LOCALAPPDATA%\Volta\tools\image\node\{node_version}\node_modules\npm`

This isn't ideal with Volta, because that means you need to specify a version of Node / npm to use, so you lose the context-sensitivity of Volta. We haven't yet had the chance to dig in deeply on IDE-specific integrations, to make things work more smoothly with the different Node versions as project switch. One place that might be worth looking is to set the Node interpreter to the _output_ of `volta which node` (similar to `$(volta which node)` in `sh`), but I'm not sure if something like that is supported by IntelliJ.

**Comment by davidgilbertson** [comment]
OK, thanks for the reply.
