### ISSUE TITLE
Volta installation on NixOS

### ISSUE THREAD

**Issue by Siilwyn** [volta-cli/volta#867]
So I'm not sure if this issue belongs here, feel free to close, however any help appreciated.

I'm trying to install Volta on [NixOS](https://nixos.org/), the installation done (in Fish) with:
```
set -x VOLTA_HOME ~/.cache/volta
curl https://get.volta.sh | bash -s -- --skip-setup
```

Installation seems to go correct however when running `volta` the terminal returns:
```
Failed to execute process '/home/siilwyn/.cache/volta/bin/volta'. Reason:
The file '/home/siilwyn/.cache/volta/bin/volta' does not exist or could not be executed.
```

While this file certainly exists:
```
~ λ ls -l /home/siilwyn/.cache/volta/bin/volta
-rwxr-xr-x 1 siilwyn users 17983744 Oct 29 20:38 /home/siilwyn/.cache/volta/bin/volta
```

I'd gladly provide more debug info if possible somehow.

**Comment by charlespierce** [comment]
Hi @Siilwyn, thanks for reaching out! Given that the file exists, my guess is that there's some binary compatibility issues causing Volta to not be executable. The installer determined the OpenSSL version correctly, so I don't think it's that. The only other library we dynamically link to (I believe) is `glibc`, so that's where I would start looking.

I'm not familiar with NixOS, but is it possible that it uses a non-GNU version of `libc`, like `musl-libc`? Alternatively, I wonder if there's a way to get more diagnostic messages out of Fish to clearly show why it couldn't execute the file. On that front, it might be worthwhile to run `bash` and then do:

```
export VOLTA_HOME=~/.cache/volta
~/.cache/volta/bin/volta --version
```

Which might give a different error and make it more clear why it couldn't execute the binary.

**Comment by Siilwyn** [comment]
Thanks for your reply, I am not sure about what version my OS uses by default but I did install the `glibc` package to be sure. (to no avail) However I have a feeling it has something to do with this because as far as I know NixOS places system stuff in unusual places it might break somewhere in that process.

Bash gives practically the same error following your two commands:
```
bash: /home/siilwyn/.cache/volta/bin/volta: No such file or directory
```

**Comment by charlespierce** [comment]
Huh, that is strange. I found this SO answer, which agrees that the problem is related to a shared library. It also gives some commands to diagnose, so that may do a better job of determining what is missing / needed: https://unix.stackexchange.com/a/413647

There's also a related answer that might help if that doesn't help: https://unix.stackexchange.com/a/13409

I'm far from an expert in Linux, but I'm happy to provide context on what Volta uses / how it's built if that will help debug the issue.

**Comment by Siilwyn** [comment]
Oh interesting!

So running `ldd ~/.cache/volta/bin/volta` gives:
```
	linux-vdso.so.1 (0x00007ffedc27e000)
	libssl.so.1.1 => not found
	libcrypto.so.1.1 => not found
	libc.so.6 => /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libc.so.6 (0x00007f4349c1e000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib64/ld-linux-x86-64.so.2 (0x00007f434a65a000)
	libdl.so.2 => /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libdl.so.2 (0x00007f4349c19000)
	librt.so.1 => /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/librt.so.1 (0x00007f4349c0f000)
	libpthread.so.0 => /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libpthread.so.0 (0x00007f4349bee000)
	libgcc_s.so.1 => /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libgcc_s.so.1 (0x00007f4349bd2000)
	libm.so.6 => /nix/store/9df65igwjmf2wbw0gbrrgair6piqjgmi-glibc-2.31/lib/libm.so.6 (0x00007f4349a91000)
```

I'll make some time soonish to figure out how to install those missing parts.

**Comment by charlespierce** [comment]
Okay, well I can definitely provide a bit of context there: `libssl.so.1.1` and `libcrypto.so.1.1` are provided by OpenSSL. However, the installer should have checked for OpenSSL by running `openssl version` internally. Since it went through, it's likely that succeeded and you _do_ have OpenSSL. However, it's also likely that it's a custom bundled version from NixOS and doesn't conform to the standard, open-source spec.

My guess, based on similar issues with CentOS, is that the NixOS version has a different `soname` (internal name for the library) than the version Volta was built against. Unfortunately, if that's the case, it's likely that none of the pre-built binaries will work, as the version you have is the only one that is built against OpenSSL 1.1.x. In that case, you may need to build from source in order to get it to work 😞 

To do that, you'll need the Rust compiler (see https://rust-lang.org to install) and then you can clone the repo and run `./dev/unix/volta-install.sh --release --skip-setup` to build and install the local version onto your machine.

**Comment by Siilwyn** [comment]
Check!

Thanks for your clear and complete reply, learned about a lot of stuff. :) I also read the discussions about Rustls, interesting stuff.

**Comment by wighawag** [comment]
@Siilwyn I installed rust and the dependencies and executed `./dev/unix/volta-install.sh --release --skip-setup` but while volta run fine and I can even install node there is 2 issues

volta is not in the path, and even when I add it to the path, node cannot be foudn, even if I find it in the  ~/.volta folder

Any idea ?

(I am very new to nixos)

**Comment by Siilwyn** [comment]
@wighawag this doesn't sound related to NixOS (I gave up on NixOS), but make sure you add the $VOLTA_HOME/bin directory, don't think $PATH looks up binaries recursively?
