### ISSUE TITLE
[Windows] error: Could not create shared environment for package 'gulp'

### ISSUE THREAD

**Issue by flexdevguy** [volta-cli/volta#928]
Does Volta require administrator Privilege to install packages ? 

`>volta install gulp`

throws the below error on Non-Admin User, if I try the same on Admin Privileged user CMD it works fine. 

```
"volta" "install" "gulp"
Volta v1.0.1

Could not create shared environment for package 'gulp'

Please ensure you have correct permissions to the Volta directory.

Error cause: A required privilege is not held by the client. (os error 1314)

```

**Comment by charlespierce** [comment]
Hi @flexdevguy, thanks for the question! Do you have [Developer Mode](https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development#accessing-settings-for-developers) turned on? Volta works by creating symlinks, so as noted in the [Getting Started](https://docs.volta.sh/guide/getting-started) guide, you either need to have Developer Mode enabled or be running as an administrator. Our recommendation is to use Developer Mode, since Volta doesn't need full administrative privileges and other tools (like `npm`) shouldn't be run as an administrator.

If you do already have Developer Mode on, then for some reason Volta isn't able to create the symlinks within the Volta directory (`%LOCALAPPDATA%\Volta\`), so my next suggestion would be to check the direct permissions on that directory.

**Comment by charlespierce** [comment]
Closing as there has been no response, but feel free to re-open if this is still a problem or if you have any further questions.

**Comment by nirtamir2** [comment]
I have the same issue with installing expo-cli

```
Volta error: Could not create shared environment for package 'expo-cli'

Please ensure you have correct permissions to the Volta directory.
```

**Comment by Aymkdn** [comment]
You can open a PowerShell/CMD as an administrator (click right then run as admin) then run the command to install global package

**Comment by charlespierce** [comment]
Hi @nirtamir2, the ability to create symlinks should be the only thing necessary. The Volta directory should be in `%LOCALAPPDATA%\Volta`, which generally maps to `C:\Users\<username>\AppData\Local\Volta`, so that's the directory you can check for permissions.

You also may need a restart after enabling developer mode (I don't remember off the top of my head, it's been a while since I turned it on), so that's another thing to try.

**Comment by nirtamir2** [comment]
I don't remember how I solved it, but my issue is resolved. Volta works perfectly on my windows machine. Thanks!

**Comment by klschm** [comment]
Hi,
I have had the same problem and solved it by copying the whole directory structure which was installed by the MSI installer to `C:\Program Files\Volta` manually to the user folder `C:\Users\<username>\AppData\Local\Volta` (because the binaries weren't there) and then it worked. So something's wrong with the MSI imo... Imo it should not install to `C:\Program Files\Volta` but to `C:\Users\<username>\AppData\Local\Volta` or the binaries from `C:\Program Files\Volta` to `C:\Users\<username>\AppData\Local\Volta` or something like this...

**Comment by robert1826** [comment]
I just had this error today and it turned out that I was in fact working with volta this whole time without enabling dev mode :D .. once it was enabled the issue disappeared, I don't see any issue with the MSI (the most recent one)

**Comment by dschulten** [comment]
On a German Windows enter "für Entwickler" while the Windows menu is open (no Cortana needed).

**Comment by webpig** [comment]
install as an administrator is work

**Comment by eleven12341241** [comment]
> Hi, I have the same issue with installing expo-cli
> 
> ```
> Volta error: Could not create shared environment for package 'expo-cli'
> 
> Please ensure you have correct permissions to the Volta directory.
> ```
> 
> @charlespierce enabled the developer mode. How to add the permissions to this directory?

Using an administrator to open cmd for installation

**Comment by prateek-cs2012** [comment]
> Hi, until a few minutes ago I have had the same problem and after fighting it for many hours now I solved it by copying the whole directory structure which was installed by the MSI installer to `C:\Program Files\Volta` manually to the user folder `C:\Users\<username>\AppData\Local\Volta` (because the binaries weren't there) and then it worked. So something's wrong with the MSI imo... Imo it should not install to `C:\Program Files\Volta` but to `C:\Users\<username>\AppData\Local\Volta` or the binaries should be copied or symlinked from `C:\Program Files\Volta` to `C:\Users\<username>\AppData\Local\Volta` or something like this...

Perfect! I spent hours on this, tried literally everything: enabling the developer mode, resetting the environment variables, restarting the PC. This worked like BANG ON!!!

**Comment by JedShiMing** [comment]
> Hi, until a few minutes ago I have had the same problem and after fighting it for many hours now I solved it by copying the whole directory structure which was installed by the MSI installer to `C:\Program Files\Volta` manually to the user folder `C:\Users\<username>\AppData\Local\Volta` (because the binaries weren't there) and then it worked. So something's wrong with the MSI imo... Imo it should not install to `C:\Program Files\Volta` but to `C:\Users\<username>\AppData\Local\Volta` or the binaries should be copied or symlinked from `C:\Program Files\Volta` to `C:\Users\<username>\AppData\Local\Volta` or something like this...

谢谢

**Comment by csj2000** [comment]
> Hi,  你好， until a few minutes ago I have had the same problem and after fighting it for many hours now I solved it by copying the whole directory structure which was installed by the MSI installer to `C:\Program Files\Volta` manually to the user folder `C:\Users\<username>\AppData\Local\Volta` (because the binaries weren't there) and then it worked.直到几分钟前我都有相同的问题，经过几个小时的努力，我通过手动将 MSI 安装程序安装的整个目录结构复制到用户文件夹中（因为那里没有二进制文件）来解决这个问题，然后它就正常工作了。 So something's wrong with the MSI imo... Imo it should not install to `C:\Program Files\Volta` but to `C:\Users\<username>\AppData\Local\Volta` or the binaries should be copied or symlinked from `C:\Program Files\Volta` to `C:\Users\<username>\AppData\Local\Volta` or something like this...MSI imo 似乎有问题...我认为它不应该安装到 `C:\Program Files\Volta` ，而应该安装到 `C:\Users\<username>\AppData\Local\Volta` ，或者应该从 `C:\Program Files\Volta` 复制或创建符号链接到 `C:\Users\<username>\AppData\Local\Volta` ，或者类似这样...

Thanks for sharing, it really helps.

**Comment by TamaraGeddert** [comment]
> Привет, [@flexdevguy](https://github.com/flexdevguy), спасибо за вопрос! У вас включен [режим разработчика](https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development#accessing-settings-for-developers)? Volta работает путем создания символических ссылок, поэтому, как указано в руководстве [«Начало работы»](https://docs.volta.sh/guide/getting-started), вам нужно либо включить режим разработчика, либо работать от имени администратора. Мы рекомендуем использовать режим разработчика, поскольку Volta не требует полных прав администратора, а другие инструменты (например, `npm`) не следует запускать от имени администратора.
> 
> Если у вас уже включён режим разработчика, то по какой-то причине Volta не может создавать символические ссылки в каталоге Volta (`%LOCALAPPDATA%\Volta\`), поэтому я бы посоветовал проверить прямые разрешения для этого каталога.

спасибо
