### ISSUE TITLE
Voltafile support: Install toolchains from file generated by `volta list --plain`

### ISSUE THREAD

**Issue by linux-china** [volta-cli/volta#931]
Most developers use dotfiles to backup configurations and recovery on different development environment.   Could volta supply same function alike brew's Brewfile, and I can backup my Volta's toolchains and recovery on different dev environments.  It's good to share my tools chains to my co-workers.

```
$ volta list --format plain  > ./Voltafile
$ volta install --bundle ./Voltafile
```

**Comment by charlespierce** [comment]
Hi @linux-china, thanks for the suggestion! Can you expand a bit on which tools you want to see backed up? For sharing, the `volta` key inside of `package.json` should handle that (that's in fact one of the things Volta was designed for): If your teammates are all using Volta as well, whenever they run `node`, `npm`, `yarn`, etc. in a project, Volta will download the version pinned in that project automatically.

For globally installed tools, our philosophy has generally been that the decision of which tools to shim is up to the individual developer. I can see a benefit of having those archived somewhere, so that when you move development environments you can make sure the tools you are used to working with are available. We also could provide a cleaner way to export your default versions, so that makes sense as well.

**Comment by linux-china** [comment]
I have installed lots of  global tools  with Volta,  such as followings: 

```
create-next-app
express-generator
vue-cli
swc
ts-node
sirv
esbuild
prettier
npm-check
emoj
typesync
...
```

and some internal tools.  These tools can be used as standalone without package.json, and migration for these tools to a new dev environment is hard, and now I use a script to manage global installations.

**Comment by charlespierce** [comment]
@linux-china That makes sense, thanks for the extra context! I definitely think there's room for some method of saving / recreating your global packages (and probably the default node / yarn versions as well).

**Comment by charlespierce** [comment]
Aha, I actually found this issue already in our backlog: #574 Closing this in favor of that, but I'll add a reference to that issue to include the additional use case!
