### ISSUE TITLE
"npm link" fails to link correctly (may be an npm v7 issue)

### ISSUE THREAD

**Issue by giltayar** [volta-cli/volta#934]
When I use `npm link` in a package (with scope), e.g. `@foo/bar` it generates a shortcut link points to a non-existing place.

So if I look in 

```shell
ls -l /Users/XXXXX/.volta/tools/image/packages/@foo/bar/lib/node_modules/@bar
```

I get `amazon-product-catalog-client -> ../../../../../../../../code/mono/packages/XXX/bar` which is _almost_ fine, except that it has too many `../`-s.

Given that there's no open issue on this, and given that I'm using npm v7 (with Node v15.7), then I'm guessing the issue is compatibility with npm v7.

**Comment by charlespierce** [comment]
Hi @giltayar, thanks for reporting! I'll do some testing, but my guess is that this is actually an issue with the scope adding an extra directory layer and that not being correctly accounted for in the process.

**Comment by giltayar** [comment]
Makes sense, although I didn't get the impression that there was only just one more `..`. I think there were much more. But I may be wrong.

**Comment by charlespierce** [comment]
Confirmed I can reproduce this and it is because of the scope in the directory structure. Interestingly, it's actually one _fewer_ `../` than is needed to make it work :smiley:

I'm going to look into a way to fix that, but it's unfortunately not completely trivial because we try to be name-agnostic as much as possible. It does appear to be emergent in npm 7, as that tries to use relative symlinks instead of absolute ones, and so runs into this issue.
