### ISSUE TITLE
volta-shim(s) not callable by capitalized extension (EXE) on Windows 10

### ISSUE THREAD

**Issue by mborejdo** [volta-cli/volta#939]
```
C:\Users\user>volta-shim.EXE
'volta-shim.EXE' is not recognized as an internal or external command
```

```
C:\Users\user>volta-shim.exe
Volta error: 'volta-shim' should not be called directly.
```

I came accross this issue from https://github.com/starship/starship/issues/2313 which recently changed the way the node-binary is called

**Comment by charlespierce** [comment]
Hi @mborejdo, thanks for reporting this! It looks like when we [determine the tool](https://github.com/volta-cli/volta/blob/main/crates/volta-core/src/run/mod.rs#L110) that is being called, we strip off `.exe` from the command, but we do it in a case-sensitive way, only stripping off `.exe`, but not `.EXE` or any other capitalizations. Since Windows files are case-insensitive, we should support any of those.

I'll get a PR up to make that a case-insensitive removal.
