### ISSUE TITLE
volta install node : Segfault - Alpine 3.13 (wsl2)

### ISSUE THREAD

**Issue by theblackhole** [volta-cli/volta#946]
Hello,

I successfully installed volta (1.0.1) in my wsl2 Alpine Linux (3.13) but when I try to install node with `volta install node`, I got a `Segmentation fault` error. I don't know how to help you diagnose this issue since there are no details about this error in volta logs (`.volta/log`)

**Comment by charlespierce** [comment]
Hi @theblackhole, thanks for reaching out! I believe the core of this issue is #473: We don't currently have a musl libc version of Volta that is compatible with Alpine Linux. I don't have much experience with musl compilation, though I know it's possible in Rust, so it may be possible to build Volta from source on that distribution.

**Comment by theblackhole** [comment]
Hello @charlespierce 
Well then I think you would mention in the docs/website/readme that Alpine isn't supported atm :) (e.g. [Getting Started](https://docs.volta.sh/guide/getting-started))

**Comment by charlespierce** [comment]
It's probably reasonable to add some sort of disclaimer. I'm not sure if the website works all that well, since it's not really feasible to have an exhaustive list of distros that we do or don't work with (especially as they all constantly change).

That said, I think we can improve the install experience to make it more robust and detect when we're on an unsupported system, instead of installing and then segfaulting afterwards.

As for snap / flatpak, I'm unfamiliar, but we do have a number of open issues around different packagers. We may want to consolidate them into a single issue so it's easier to track. Ultimately, supporting different packaging systems comes down to whether or not we can reasonably maintain them as part of the release process (or if people are open to taking ownership of keeping them up-to-date).

**Comment by vanstinator** [comment]
FWIW I was able to trivially build volta in alpine. It'll install node just fine. But the shims can't seem to find it (even with the paths set up correctly). This being alpine there's a chance I had a missing dependency that wasn't logged even with backtraces and debug logging turned on. If I have time in the next few weeks I may try getting an alpine install running in WSL 2 as well so I can more easily debug what is going on.

**Comment by charlespierce** [comment]
@vanstinator Glad to hear it was compiling easily, that makes it much more likely it will be straightforward to set up a pre-compiled version! I'm happy to help you debug if needed, just let me know either here or on Discord!
