### ISSUE TITLE
`volta list` - Limit parsing package config files to those that have a `json` extension

### ISSUE THREAD

**Issue by dwiyatci** [volta-cli/volta#980]
Hello 👋 

I'm on Volta 1.04, and when I executed `volta list`, I got:
```
➜  ~ volta list     
[verbose] Found default configuration at '/Users/glenn/.volta/tools/user/platform.json'
error: Could not parse package configuration file.

Please rerun the command that triggered this error with the environment
variable `VOLTA_LOGLEVEL` set to `debug` and open an issue at
https://github.com/volta-cli/volta/issues with the details!
[verbose] Error cause: expected value at line 1 column 1
Error details written to /Users/glenn/.volta/log/volta-error-2021-04-28_13_56_53.370.log
[verbose] No custom hooks found
➜  ~ volta --version
1.0.4
[verbose] No custom hooks found
➜  ~ 
```

I've set the `VOLTA_LOGLEVEL` to `debug` and also checked the log but it didn't give me more info other than **"Error cause: expected value at line 1 column 1"**. Any insights? 🤔 

Thank you.

**Comment by dwiyatci** [comment]
@chriskrycho Ah ok, thanks. But which `package.json` are you referring to here? 🤔🤔

**Comment by charlespierce** [comment]
I just did a double-check in the code, and the `package configuration file` referenced here is actually the internal package metadata that we store for a globally-installed package. Those files should be auto-generated by Volta and so should be written correctly and not have to be managed. That said, we probably should update that error message to include the file that we're opening to make it easier to track down the issue.

Based on the actual parse error, it looks like there may be one of those files that was written with 0 length, so it's trying to parse the data out of it, but there isn't any data. @dwiyatci All of those files should be in `~/.volta/tools/user/packages/` and named `{package name}.json`. If you can locate one there that is empty or otherwise corrupted, that file probably needs to be deleted (and the associated package re-installed with either `volta install <package>`, `npm i -g <package>`, or `yarn global add <package>`)

**Comment by dwiyatci** [comment]
Thank you @charlespierce for the detailed and comprehensive troubleshooting explanation/instruction. I checked all the `{package-name}.json` files under that `~/.volta/tools/user/packages/` directory but all seemed to have _**non-zero**_ bytes length and _**not**_ malformed. I then also tried to reinstall all the packages that are managed by `npm` and `yarn` respectively -- but still no luck 😕 

Is there anything else that I could try? And is there such thing as "re-installing" Volta?

Additional context: I actually installed Volta via Homebrew, but not sure if this is relevant. It was running well for around one good hour, but then unfortunately I got this issue.

**Comment by charlespierce** [comment]
@dwiyatci That's very odd. Homebrew shouldn't be an issue, as the data files in question are in `~/.volta` anyway. One thing that may be happening (I haven't seen this, but I've seen other odd failures): Is it possible you have an older version of Volta in `~/.volta` that things are linked to? The way to check would be to see the output of `ls -l ~/.volta/bin` and look for whether or not there are `volta-*` binary files there as well as the source of the symlinks. Alternatively, you could look at `which -a volta` and see if there are multiple sources of the binary.

Apart from that, there are a few ways to reset the system: The easiest (though most destructive) would be to delete the entire `~/.volta` directory and then run `volta setup` (since it's from Homebrew, `volta` should still be available as a command). That will completely regenerate the data directory, but it will also delete all of your Node versions and packages, so you'll want to re-install anything you were using.

A little less destructive would be to go through each of the packages that have files in `~/.volta/tools/user/packages/` and run `volta uninstall <package>`, then go back through after that and re-install them. That should delete and rebuild all of the configuration files, but would fail to fix an issue of multiple versions.

**Comment by dwiyatci** [comment]
Ok, this might sound a bit crazy but:

`ls -l ~/.volta/bin` and/or `which -a volta` seemed to look fine for me (no multiple sources/versions of binary whatsoever; this is the first time I install Volta).

I went for the less destructive way you suggested above, and ran `volta uninstall <package>` till the `~/.volta/tools/user/packages/` directory got empty, still got the error.

And then I thought "screw this `packages` folder" and removed the `~/.volta/tools/user/packages/` itself and recreated it again manually, it made the error gone somehow in the end 🤷🏻‍♂️

**Comment by charlespierce** [comment]
Oh that's a big hint, and I think I might know what was happening: Part of `volta list` is it reads all of the files in that directory to determine all of the installed packages. However, if you at some point opened that folder in Finder, MacOS may have created a `.DS_Store` hidden file. Then when `volta list` read all of the files, it tried to open that as a JSON and failed :scream:

I think we can solve that by updating the logic to only try to load files with the `.json` extension, instead of trying to read everything.

**Comment by dwiyatci** [comment]
AH, YOU'RE DAMN RIGHT!! I tried to explore the structure of `.volta`'s directory using Finder before this problem occurred. 

Well, at least I learned quite something (more than something) about Volta's directories layout today ⚡ 😅

**Comment by dwiyatci** [comment]
...and I can confirm this is reproducible when I got that `.DS_Store` file back in the dir. 👍

**Comment by charlespierce** [comment]
:scream: Okay, glad we figured it out (and curse you MacOS!). This should be a relatively simple thing to fix so that it doesn't crop up again. Thanks for confirming!
