### ISSUE TITLE
What's the easiest way to update Volta to a newer version on Windows 10?

### ISSUE THREAD

**Issue by nemonemi** [volta-cli/volta#982]
There doesn't seem to be documentation on this topic.
Please correct me if I'm wrong.

**Comment by charlespierce** [comment]
Hi @nemonemi, thanks for asking! We should definitely update the docs, however to answer your question, the easiest way to update Volta is to run the installer `.msi` file for the new version. The installer will automatically detect the previous version and remove it while upgrading to the latest, so that should take care of the update for you.

**Comment by nemonemi** [comment]
Thanks @charlespierce!
